use super::StdlibFunctionDetails;

pub fn docs() -> Vec<StdlibFunctionDetails> {
    vec![
        super::stdlib_doc!("capricorn", "accept_invite", return_type: "CapricornTeamOperationInfo", "执行摩羯宫的 accept_invite 操作。", params: ["uin" => "玩家 UIN。"], returns: "返回 CapricornTeamOperationInfo。", examples: ["let result = capricorn::accept_invite(0);"]),
        super::stdlib_doc!("capricorn", "cancel_invite", return_type: "CapricornTeamOperationInfo", "执行摩羯宫的 cancel_invite 操作。", params: [], returns: "返回 CapricornTeamOperationInfo。", examples: ["let result = capricorn::cancel_invite();"]),
        super::stdlib_doc!("capricorn", "disband_team", return_type: "CapricornTeamOperationInfo", "执行摩羯宫的 disband_team 操作。", params: [], returns: "返回 CapricornTeamOperationInfo。", examples: ["let result = capricorn::disband_team();"]),
        super::stdlib_doc!("capricorn", "invite_player", return_type: "CapricornTeamOperationInfo", "执行摩羯宫的 invite_player 操作。", params: ["uin" => "玩家 UIN。"], returns: "返回 CapricornTeamOperationInfo。", examples: ["let result = capricorn::invite_player(0);"]),
        super::stdlib_doc!("capricorn", "leave_team", return_type: "CapricornTeamOperationInfo", "执行摩羯宫的 leave_team 操作。", params: [], returns: "返回 CapricornTeamOperationInfo。", examples: ["let result = capricorn::leave_team();"]),
        super::stdlib_doc!("capricorn", "query_invite_list", return_type: "CapricornInviteListInfo", "查询摩羯宫的 query_invite_list 操作。", params: [], returns: "返回 CapricornInviteListInfo。", examples: ["let result = capricorn::query_invite_list();"]),
        super::stdlib_doc!("capricorn", "query_palace_notes", return_type: "CapricornPalaceNotesInfo", "查询摩羯宫的 query_palace_notes 操作。", params: [], returns: "返回 CapricornPalaceNotesInfo。", examples: ["let result = capricorn::query_palace_notes();"]),
        super::stdlib_doc!("capricorn", "refuse_invite", return_type: "CapricornTeamOperationInfo", "执行摩羯宫的 refuse_invite 操作。", params: ["uin" => "玩家 UIN。"], returns: "返回 CapricornTeamOperationInfo。", examples: ["let result = capricorn::refuse_invite(0);"]),
        super::stdlib_doc!("capricorn", "second_accept_task", return_type: "CapricornSecondInfo", "执行摩羯宫的 second_accept_task 操作。", params: [], returns: "返回 CapricornSecondInfo。", examples: ["let result = capricorn::second_accept_task();"]),
        super::stdlib_doc!("capricorn", "second_answer_quiz", return_type: "CapricornSecondInfo", "执行摩羯宫的 second_answer_quiz 操作。", params: ["answer_index" => "答案索引。"], returns: "返回 CapricornSecondInfo。", examples: ["let result = capricorn::second_answer_quiz(0);"]),
        super::stdlib_doc!("capricorn", "second_buy_up", return_type: "CapricornSecondInfo", "购买摩羯宫的 second_buy_up 操作。", params: ["spirit_id" => "宠物 ID。", "catch_time" => "宠物捕获时间。"], returns: "返回 CapricornSecondInfo。", examples: ["let result = capricorn::second_buy_up(0, 0);"]),
        super::stdlib_doc!("capricorn", "second_evolve", return_type: "CapricornSecondInfo", "提升摩羯宫的 second_evolve 操作。", params: ["spirit_id" => "宠物 ID。", "catch_time" => "宠物捕获时间。"], returns: "返回 CapricornSecondInfo。", examples: ["let result = capricorn::second_evolve(0, 0);"]),
        super::stdlib_doc!("capricorn", "second_give_up_task", return_type: "CapricornSecondInfo", "执行摩羯宫的 second_give_up_task 操作。", params: [], returns: "返回 CapricornSecondInfo。", examples: ["let result = capricorn::second_give_up_task();"]),
        super::stdlib_doc!("capricorn", "second_level_up", return_type: "CapricornSecondInfo", "提升摩羯宫的 second_level_up 操作。", params: ["spirit_id" => "宠物 ID。", "catch_time" => "宠物捕获时间。"], returns: "返回 CapricornSecondInfo。", examples: ["let result = capricorn::second_level_up(0, 0);"]),
        super::stdlib_doc!("capricorn", "second_query", return_type: "CapricornSecondInfo", "查询摩羯宫的 second_query 操作。", params: [], returns: "返回 CapricornSecondInfo。", examples: ["let result = capricorn::second_query();"]),
        super::stdlib_doc!("capricorn", "second_query_bag", return_type: "CapricornSecondInfo", "查询摩羯宫的 second_query_bag 操作。", params: ["kind" => "业务类型。"], returns: "返回 CapricornSecondInfo。", examples: ["let result = capricorn::second_query_bag(0);"]),
        super::stdlib_doc!("capricorn", "second_random_task", return_type: "CapricornSecondInfo", "执行摩羯宫的 second_random_task 操作。", params: [], returns: "返回 CapricornSecondInfo。", examples: ["let result = capricorn::second_random_task();"]),
        super::stdlib_doc!("capricorn", "submit_second_combat_task", return_type: "CapricornSecondInfo", "提交摩羯宫的 submit_second_combat_task 操作。", params: [], returns: "返回 CapricornSecondInfo。", examples: ["let result = capricorn::submit_second_combat_task();"]),
        super::stdlib_doc!("capricorn", "star_palace_quick_summon", return_type: "CapricornStarPalaceInfo", "执行摩羯宫的 star_palace_quick_summon 操作。", params: [], returns: "返回 CapricornStarPalaceInfo。", examples: ["let result = capricorn::star_palace_quick_summon();"]),
        super::stdlib_doc!("capricorn", "star_palace_summon", return_type: "CapricornStarPalaceInfo", "执行摩羯宫的 star_palace_summon 操作。", params: [], returns: "返回 CapricornStarPalaceInfo。", examples: ["let result = capricorn::star_palace_summon();"]),
        super::stdlib_doc!("capricorn", "third_add_challenge_count", return_type: "CapricornThirdInfo", "更新摩羯宫的 third_add_challenge_count 操作。", params: [], returns: "返回 CapricornThirdInfo。", examples: ["let result = capricorn::third_add_challenge_count();"]),
        super::stdlib_doc!("capricorn", "third_buy_progress", return_type: "CapricornThirdInfo", "购买摩羯宫的 third_buy_progress 操作。", params: ["spirit_id" => "宠物 ID。", "catch_time" => "宠物捕获时间。"], returns: "返回 CapricornThirdInfo。", examples: ["let result = capricorn::third_buy_progress(0, 0);"]),
        super::stdlib_doc!("capricorn", "third_buy_star_item", return_type: "CapricornThirdInfo", "购买摩羯宫的 third_buy_star_item 操作。", params: [], returns: "返回 CapricornThirdInfo。", examples: ["let result = capricorn::third_buy_star_item();"]),
        super::stdlib_doc!("capricorn", "third_buy_star_num", return_type: "CapricornThirdInfo", "购买摩羯宫的 third_buy_star_num 操作。", params: [], returns: "返回 CapricornThirdInfo。", examples: ["let result = capricorn::third_buy_star_num();"]),
        super::stdlib_doc!("capricorn", "third_evolve", return_type: "CapricornThirdInfo", "提升摩羯宫的 third_evolve 操作。", params: ["spirit_id" => "宠物 ID。", "catch_time" => "宠物捕获时间。"], returns: "返回 CapricornThirdInfo。", examples: ["let result = capricorn::third_evolve(0, 0);"]),
        super::stdlib_doc!("capricorn", "third_query", return_type: "CapricornThirdInfo", "查询摩羯宫的 third_query 操作。", params: [], returns: "返回 CapricornThirdInfo。", examples: ["let result = capricorn::third_query();"]),
        super::stdlib_doc!("capricorn", "third_query_bag", return_type: "CapricornThirdInfo", "查询摩羯宫的 third_query_bag 操作。", params: [], returns: "返回 CapricornThirdInfo。", examples: ["let result = capricorn::third_query_bag();"]),
        super::stdlib_doc!("capricorn", "submit_third", return_type: "CapricornThirdInfo", "提交摩羯宫的 submit_third 操作。", params: ["boss_index" => "首领索引。"], returns: "返回 CapricornThirdInfo。", examples: ["let result = capricorn::submit_third(0);"]),
    ]
}
