use super::StdlibFunctionRegistration;

pub const FUNCTIONS: &[StdlibFunctionRegistration] = &[
    StdlibFunctionRegistration::new("adventure", "claim_daily", "adventure::claim_daily()"),
    StdlibFunctionRegistration::new("adventure", "claim_reward", "adventure::claim_reward(point: int)"),
    StdlibFunctionRegistration::new("adventure", "end_auto", "adventure::end_auto(point: int)"),
    StdlibFunctionRegistration::new("adventure", "end_auto_vip", "adventure::end_auto_vip(point: int)"),
    StdlibFunctionRegistration::new("adventure", "query_status", "adventure::query_status()"),
    StdlibFunctionRegistration::new("adventure", "start", "adventure::start(point: int)"),
    StdlibFunctionRegistration::new("adventure", "start_auto", "adventure::start_auto(point: int, count: int)"),
    StdlibFunctionRegistration::new("alchemy_furnace", "monkey_cultivation_claim_gift", "alchemy_furnace::monkey_cultivation_claim_gift()"),
    StdlibFunctionRegistration::new("alchemy_furnace", "monkey_cultivation_query", "alchemy_furnace::monkey_cultivation_query()"),
    StdlibFunctionRegistration::new("alchemy_furnace", "monkey_evo_claim_gift", "alchemy_furnace::monkey_evo_claim_gift()"),
    StdlibFunctionRegistration::new("alchemy_furnace", "monkey_evo_evolve", "alchemy_furnace::monkey_evo_evolve(catch_time: int)"),
    StdlibFunctionRegistration::new("alchemy_furnace", "monkey_evo_give_up", "alchemy_furnace::monkey_evo_give_up()"),
    StdlibFunctionRegistration::new("alchemy_furnace", "monkey_evo_query", "alchemy_furnace::monkey_evo_query()"),
    StdlibFunctionRegistration::new("alchemy_furnace", "monkey_evo_query_bag", "alchemy_furnace::monkey_evo_query_bag()"),
    StdlibFunctionRegistration::new("alchemy_furnace", "raging_fire_buy", "alchemy_furnace::raging_fire_buy(spirit_id: int, catch_time: int)"),
    StdlibFunctionRegistration::new("alchemy_furnace", "raging_fire_claim_gift", "alchemy_furnace::raging_fire_claim_gift(spirit_id: int, catch_time: int)"),
    StdlibFunctionRegistration::new("alchemy_furnace", "raging_fire_query", "alchemy_furnace::raging_fire_query()"),
    StdlibFunctionRegistration::new("alchemy_furnace", "raging_fire_query_bag", "alchemy_furnace::raging_fire_query_bag()"),
    StdlibFunctionRegistration::new("alchemy_furnace", "submit_monkey_cultivation_default", "alchemy_furnace::submit_monkey_cultivation_default()"),
    StdlibFunctionRegistration::new("alchemy_furnace", "submit_monkey_cultivation_pills", "alchemy_furnace::submit_monkey_cultivation_pills(dragon_tiger: bool, cultivate_origin: bool, nine_turn: bool)"),
    StdlibFunctionRegistration::new("alchemy_furnace", "submit_monkey_evo_combat", "alchemy_furnace::submit_monkey_evo_combat(combat_type: int)"),
    StdlibFunctionRegistration::new("alchemy_furnace", "submit_monkey_evo_default", "alchemy_furnace::submit_monkey_evo_default()"),
    StdlibFunctionRegistration::new("alchemy_furnace", "submit_monkey_evo_pills", "alchemy_furnace::submit_monkey_evo_pills(dragon_tiger: bool, cultivate_origin: bool, nine_turn: bool)"),
    StdlibFunctionRegistration::new("alchemy_furnace", "submit_raging_fire_combat", "alchemy_furnace::submit_raging_fire_combat(target: int)"),
    StdlibFunctionRegistration::new("alchemy_furnace", "submit_raging_fire_stone", "alchemy_furnace::submit_raging_fire_stone(count: int)"),
    StdlibFunctionRegistration::new("aquarius", "first_add_challenge_count", "aquarius::first_add_challenge_count()"),
    StdlibFunctionRegistration::new("aquarius", "first_buy_direct", "aquarius::first_buy_direct(item_or_spirit_id: int, count: int)"),
    StdlibFunctionRegistration::new("aquarius", "first_buy_evolve_access", "aquarius::first_buy_evolve_access(spirit_id: int, catch_time: int)"),
    StdlibFunctionRegistration::new("aquarius", "first_buy_star_num", "aquarius::first_buy_star_num()"),
    StdlibFunctionRegistration::new("aquarius", "first_evolve", "aquarius::first_evolve(spirit_id: int, catch_time: int)"),
    StdlibFunctionRegistration::new("aquarius", "first_query", "aquarius::first_query()"),
    StdlibFunctionRegistration::new("aquarius", "first_query_bag", "aquarius::first_query_bag()"),
    StdlibFunctionRegistration::new("aquarius", "second_buy_spirit", "aquarius::second_buy_spirit()"),
    StdlibFunctionRegistration::new("aquarius", "second_buy_tail", "aquarius::second_buy_tail(count: int)"),
    StdlibFunctionRegistration::new("aquarius", "second_buy_wish", "aquarius::second_buy_wish()"),
    StdlibFunctionRegistration::new("aquarius", "second_combat_again", "aquarius::second_combat_again()"),
    StdlibFunctionRegistration::new("aquarius", "second_exchange_item", "aquarius::second_exchange_item(exchange_position: int)"),
    StdlibFunctionRegistration::new("aquarius", "second_exchange_spirit", "aquarius::second_exchange_spirit()"),
    StdlibFunctionRegistration::new("aquarius", "second_query_diamond", "aquarius::second_query_diamond()"),
    StdlibFunctionRegistration::new("aquarius", "second_query_status", "aquarius::second_query_status()"),
    StdlibFunctionRegistration::new("aquarius", "submit_first", "aquarius::submit_first(boss_index: int)"),
    StdlibFunctionRegistration::new("aquarius", "submit_third", "aquarius::submit_third()"),
    StdlibFunctionRegistration::new("aquarius", "third_buy_evolve", "aquarius::third_buy_evolve(spirit_id: int, catch_time: int)"),
    StdlibFunctionRegistration::new("aquarius", "third_buy_level", "aquarius::third_buy_level()"),
    StdlibFunctionRegistration::new("aquarius", "third_evolve", "aquarius::third_evolve(spirit_id: int, catch_time: int)"),
    StdlibFunctionRegistration::new("aquarius", "third_query", "aquarius::third_query()"),
    StdlibFunctionRegistration::new("aquarius", "third_query_bag", "aquarius::third_query_bag(bag_type: int)"),
    StdlibFunctionRegistration::new("aquarius", "third_random", "aquarius::third_random()"),
    StdlibFunctionRegistration::new("aries", "first_buy_direct", "aries::first_buy_direct()"),
    StdlibFunctionRegistration::new("aries", "first_buy_times", "aries::first_buy_times()"),
    StdlibFunctionRegistration::new("aries", "first_dice", "aries::first_dice()"),
    StdlibFunctionRegistration::new("aries", "first_evolve", "aries::first_evolve(spirit_id: int, catch_time: int)"),
    StdlibFunctionRegistration::new("aries", "first_get_gold", "aries::first_get_gold()"),
    StdlibFunctionRegistration::new("aries", "first_level_up", "aries::first_level_up(spirit_id: int, catch_time: int)"),
    StdlibFunctionRegistration::new("aries", "first_query", "aries::first_query()"),
    StdlibFunctionRegistration::new("aries", "first_query_bag", "aries::first_query_bag()"),
    StdlibFunctionRegistration::new("aries", "first_start", "aries::first_start()"),
    StdlibFunctionRegistration::new("aries", "second_buy_direct", "aries::second_buy_direct()"),
    StdlibFunctionRegistration::new("aries", "second_buy_level", "aries::second_buy_level(spirit_id: int, catch_time: int)"),
    StdlibFunctionRegistration::new("aries", "second_evolve", "aries::second_evolve(spirit_id: int, catch_time: int)"),
    StdlibFunctionRegistration::new("aries", "second_query", "aries::second_query()"),
    StdlibFunctionRegistration::new("aries", "second_query_bag", "aries::second_query_bag()"),
    StdlibFunctionRegistration::new("aries", "submit_first", "aries::submit_first(combat_type: int)"),
    StdlibFunctionRegistration::new("aries", "submit_second_game", "aries::submit_second_game(power: int)"),
    StdlibFunctionRegistration::new("aries", "third_buy_tail", "aries::third_buy_tail(count: int)"),
    StdlibFunctionRegistration::new("aries", "third_buy_wish", "aries::third_buy_wish()"),
    StdlibFunctionRegistration::new("aries", "third_exchange_item", "aries::third_exchange_item(exchange_position: int)"),
    StdlibFunctionRegistration::new("aries", "third_exchange_spirit", "aries::third_exchange_spirit()"),
    StdlibFunctionRegistration::new("aries", "third_query_status", "aries::third_query_status()"),
    StdlibFunctionRegistration::new("cancer", "mend_shape_buy", "cancer::mend_shape_buy(buy_type: int)"),
    StdlibFunctionRegistration::new("cancer", "mend_shape_buy_full", "cancer::mend_shape_buy_full(spirit_id: int, catch_time: int)"),
    StdlibFunctionRegistration::new("cancer", "mend_shape_query", "cancer::mend_shape_query()"),
    StdlibFunctionRegistration::new("cancer", "mend_shape_query_bag", "cancer::mend_shape_query_bag()"),
    StdlibFunctionRegistration::new("cancer", "mend_shape_upgrade", "cancer::mend_shape_upgrade(spirit_id: int, catch_time: int)"),
    StdlibFunctionRegistration::new("cancer", "mend_shape_upgrade_to_100", "cancer::mend_shape_upgrade_to_100(spirit_id: int, catch_time: int)"),
    StdlibFunctionRegistration::new("cancer", "sharp_scorpion_buy_tail", "cancer::sharp_scorpion_buy_tail(num: int)"),
    StdlibFunctionRegistration::new("cancer", "sharp_scorpion_buy_wish", "cancer::sharp_scorpion_buy_wish()"),
    StdlibFunctionRegistration::new("cancer", "sharp_scorpion_exchange_item", "cancer::sharp_scorpion_exchange_item(exc_pos: int)"),
    StdlibFunctionRegistration::new("cancer", "sharp_scorpion_exchange_spirit", "cancer::sharp_scorpion_exchange_spirit()"),
    StdlibFunctionRegistration::new("cancer", "sharp_scorpion_query", "cancer::sharp_scorpion_query()"),
    StdlibFunctionRegistration::new("cancer", "submit_unseal_memories_choice", "cancer::submit_unseal_memories_choice(choice: int)"),
    StdlibFunctionRegistration::new("cancer", "unseal_memories_bag_query", "cancer::unseal_memories_bag_query()"),
    StdlibFunctionRegistration::new("cancer", "unseal_memories_buy", "cancer::unseal_memories_buy(buy_type: int)"),
    StdlibFunctionRegistration::new("cancer", "unseal_memories_put_full", "cancer::unseal_memories_put_full(spirit_id: int, catch_time: int)"),
    StdlibFunctionRegistration::new("cancer", "unseal_memories_query", "cancer::unseal_memories_query()"),
    StdlibFunctionRegistration::new("cancer", "unseal_memories_start_game", "cancer::unseal_memories_start_game()"),
    StdlibFunctionRegistration::new("capricorn", "accept_invite", "capricorn::accept_invite(uin: int)"),
    StdlibFunctionRegistration::new("capricorn", "cancel_invite", "capricorn::cancel_invite()"),
    StdlibFunctionRegistration::new("capricorn", "disband_team", "capricorn::disband_team()"),
    StdlibFunctionRegistration::new("capricorn", "invite_player", "capricorn::invite_player(uin: int)"),
    StdlibFunctionRegistration::new("capricorn", "leave_team", "capricorn::leave_team()"),
    StdlibFunctionRegistration::new("capricorn", "query_invite_list", "capricorn::query_invite_list()"),
    StdlibFunctionRegistration::new("capricorn", "query_palace_notes", "capricorn::query_palace_notes()"),
    StdlibFunctionRegistration::new("capricorn", "refuse_invite", "capricorn::refuse_invite(uin: int)"),
    StdlibFunctionRegistration::new("capricorn", "second_accept_task", "capricorn::second_accept_task()"),
    StdlibFunctionRegistration::new("capricorn", "second_answer_quiz", "capricorn::second_answer_quiz(answer_index: int)"),
    StdlibFunctionRegistration::new("capricorn", "second_buy_up", "capricorn::second_buy_up(spirit_id: int, catch_time: int)"),
    StdlibFunctionRegistration::new("capricorn", "second_evolve", "capricorn::second_evolve(spirit_id: int, catch_time: int)"),
    StdlibFunctionRegistration::new("capricorn", "second_give_up_task", "capricorn::second_give_up_task()"),
    StdlibFunctionRegistration::new("capricorn", "second_level_up", "capricorn::second_level_up(spirit_id: int, catch_time: int)"),
    StdlibFunctionRegistration::new("capricorn", "second_query", "capricorn::second_query()"),
    StdlibFunctionRegistration::new("capricorn", "second_query_bag", "capricorn::second_query_bag(kind: int)"),
    StdlibFunctionRegistration::new("capricorn", "second_random_task", "capricorn::second_random_task()"),
    StdlibFunctionRegistration::new("capricorn", "star_palace_quick_summon", "capricorn::star_palace_quick_summon()"),
    StdlibFunctionRegistration::new("capricorn", "star_palace_summon", "capricorn::star_palace_summon()"),
    StdlibFunctionRegistration::new("capricorn", "submit_second_combat_task", "capricorn::submit_second_combat_task()"),
    StdlibFunctionRegistration::new("capricorn", "submit_third", "capricorn::submit_third(boss_index: int)"),
    StdlibFunctionRegistration::new("capricorn", "third_add_challenge_count", "capricorn::third_add_challenge_count()"),
    StdlibFunctionRegistration::new("capricorn", "third_buy_progress", "capricorn::third_buy_progress(spirit_id: int, catch_time: int)"),
    StdlibFunctionRegistration::new("capricorn", "third_buy_star_item", "capricorn::third_buy_star_item()"),
    StdlibFunctionRegistration::new("capricorn", "third_buy_star_num", "capricorn::third_buy_star_num()"),
    StdlibFunctionRegistration::new("capricorn", "third_evolve", "capricorn::third_evolve(spirit_id: int, catch_time: int)"),
    StdlibFunctionRegistration::new("capricorn", "third_query", "capricorn::third_query()"),
    StdlibFunctionRegistration::new("capricorn", "third_query_bag", "capricorn::third_query_bag()"),
    StdlibFunctionRegistration::new("combat", "can_capture", "combat::can_capture()"),
    StdlibFunctionRegistration::new("combat", "can_change_to_spirit", "combat::can_change_to_spirit(position: int)"),
    StdlibFunctionRegistration::new("combat", "can_use_item", "combat::can_use_item(item_id: int)"),
    StdlibFunctionRegistration::new("combat", "can_use_skill", "combat::can_use_skill(skill_id: int)"),
    StdlibFunctionRegistration::new("combat", "change_spirit", "combat::change_spirit(position: int)"),
    StdlibFunctionRegistration::new("combat", "escape", "combat::escape()"),
    StdlibFunctionRegistration::new("combat", "get_action_snapshot", "combat::get_action_snapshot()"),
    StdlibFunctionRegistration::new("combat", "get_actions", "combat::get_actions()"),
    StdlibFunctionRegistration::new("combat", "get_current_round", "combat::get_current_round()"),
    StdlibFunctionRegistration::new("combat", "get_history", "combat::get_history()"),
    StdlibFunctionRegistration::new("combat", "get_lineup", "combat::get_lineup()"),
    StdlibFunctionRegistration::new("combat", "get_my_hp", "combat::get_my_hp()"),
    StdlibFunctionRegistration::new("combat", "get_my_max_hp", "combat::get_my_max_hp()"),
    StdlibFunctionRegistration::new("combat", "get_my_pp", "combat::get_my_pp(slot: int)"),
    StdlibFunctionRegistration::new("combat", "get_my_spirit_info", "combat::get_my_spirit_info(position: int)"),
    StdlibFunctionRegistration::new("combat", "get_result", "combat::get_result()"),
    StdlibFunctionRegistration::new("combat", "get_rival_hp", "combat::get_rival_hp()"),
    StdlibFunctionRegistration::new("combat", "get_rival_max_hp", "combat::get_rival_max_hp()"),
    StdlibFunctionRegistration::new("combat", "get_rival_spirit_info", "combat::get_rival_spirit_info()"),
    StdlibFunctionRegistration::new("combat", "get_state", "combat::get_state()"),
    StdlibFunctionRegistration::new("combat", "is_finished", "combat::is_finished()"),
    StdlibFunctionRegistration::new("combat", "start_combat", "combat::start_combat(server_type: int, combat_type: int, rival_id: int, catch_time: int)"),
    StdlibFunctionRegistration::new("combat", "try_change_spirit", "combat::try_change_spirit(position: int)"),
    StdlibFunctionRegistration::new("combat", "try_change_spirit_and_wait", "combat::try_change_spirit_and_wait(position: int)"),
    StdlibFunctionRegistration::new("combat", "try_escape", "combat::try_escape()"),
    StdlibFunctionRegistration::new("combat", "try_escape_and_wait", "combat::try_escape_and_wait()"),
    StdlibFunctionRegistration::new("combat", "try_get_result", "combat::try_get_result()"),
    StdlibFunctionRegistration::new("combat", "try_use_item", "combat::try_use_item(item_id: int)"),
    StdlibFunctionRegistration::new("combat", "try_use_skill", "combat::try_use_skill(skill_id: int)"),
    StdlibFunctionRegistration::new("combat", "try_use_skill_and_wait", "combat::try_use_skill_and_wait(skill_id: int)"),
    StdlibFunctionRegistration::new("combat", "use_item", "combat::use_item(item_id: int)"),
    StdlibFunctionRegistration::new("combat", "use_skill", "combat::use_skill(skill_id: int)"),
    StdlibFunctionRegistration::new("combat", "wait_next_action", "combat::wait_next_action()"),
    StdlibFunctionRegistration::new("combat", "wait_round_end", "combat::wait_round_end()"),
    StdlibFunctionRegistration::new("combat_result", "name", "combat_result::name(result: int)"),
    StdlibFunctionRegistration::new("combat_result", "names", "combat_result::names()"),
    StdlibFunctionRegistration::new("combat_status", "name", "combat_status::name(status: int)"),
    StdlibFunctionRegistration::new("combat_status", "names", "combat_status::names()"),
    StdlibFunctionRegistration::new("dark_city", "expedition_query", "dark_city::expedition_query()"),
    StdlibFunctionRegistration::new("dark_city", "expedition_set_vip_pass", "dark_city::expedition_set_vip_pass(enabled: bool)"),
    StdlibFunctionRegistration::new("dark_city", "expedition_start_combat", "dark_city::expedition_start_combat(vip_boost: bool)"),
    StdlibFunctionRegistration::new("dark_city", "reputation_exchange", "dark_city::reputation_exchange(index: int, count: int)"),
    StdlibFunctionRegistration::new("dark_city", "reputation_query_exchange", "dark_city::reputation_query_exchange()"),
    StdlibFunctionRegistration::new("dark_city", "submit_expedition", "dark_city::submit_expedition()"),
    StdlibFunctionRegistration::new("diamond_tear", "buy_spirit", "diamond_tear::buy_spirit()"),
    StdlibFunctionRegistration::new("diamond_tear", "claim_diamond", "diamond_tear::claim_diamond()"),
    StdlibFunctionRegistration::new("diamond_tear", "freeze", "diamond_tear::freeze()"),
    StdlibFunctionRegistration::new("diamond_tear", "query", "diamond_tear::query()"),
    StdlibFunctionRegistration::new("four_seasons", "claim_spirit_reward", "four_seasons::claim_spirit_reward(index: int)"),
    StdlibFunctionRegistration::new("four_seasons", "exchange_shop_item", "four_seasons::exchange_shop_item(slot: int)"),
    StdlibFunctionRegistration::new("four_seasons", "query", "four_seasons::query()"),
    StdlibFunctionRegistration::new("four_seasons", "roll_dice", "four_seasons::roll_dice(vip: bool)"),
    StdlibFunctionRegistration::new("four_seasons", "submit_event", "four_seasons::submit_event()"),
    StdlibFunctionRegistration::new("four_seasons", "submit_mini_game", "four_seasons::submit_mini_game()"),
    StdlibFunctionRegistration::new("four_seasons", "upgrade_box", "four_seasons::upgrade_box(position: int)"),
    StdlibFunctionRegistration::new("four_seasons", "use_appointed_step_tool", "four_seasons::use_appointed_step_tool(step: int)"),
    StdlibFunctionRegistration::new("four_seasons", "use_tool", "four_seasons::use_tool(tool: int)"),
    StdlibFunctionRegistration::new("friend", "delete", "friend::delete(friend_uin: int)"),
    StdlibFunctionRegistration::new("friend", "handle_application", "friend::handle_application(sender_uin: int, accept: bool)"),
    StdlibFunctionRegistration::new("friend", "query_details", "friend::query_details(friend_uins: array)"),
    StdlibFunctionRegistration::new("friend", "query_initial_state", "friend::query_initial_state()"),
    StdlibFunctionRegistration::new("friend", "query_online", "friend::query_online()"),
    StdlibFunctionRegistration::new("friend", "send_application", "friend::send_application(friend_uin: int)"),
    StdlibFunctionRegistration::new("friend", "send_chat", "friend::send_chat(friend_uin: int, message: string)"),
    StdlibFunctionRegistration::new("game", "is_paused", "game::is_paused()"),
    StdlibFunctionRegistration::new("game", "set_paused", "game::set_paused(enabled: bool)"),
    StdlibFunctionRegistration::new("game", "start_mini_game", "game::start_mini_game(game_id: int)"),
    StdlibFunctionRegistration::new("game", "submit_mini_game_score", "game::submit_mini_game_score(game_id: int, score: int, game_type: int)"),
    StdlibFunctionRegistration::new("game", "try_set_paused", "game::try_set_paused(enabled: bool)"),
    StdlibFunctionRegistration::new("game", "try_submit_mini_game_score", "game::try_submit_mini_game_score(game_id: int, score: int, game_type: int)"),
    StdlibFunctionRegistration::new("gemini", "first_buy_evolve_access", "gemini::first_buy_evolve_access(catch_time: int)"),
    StdlibFunctionRegistration::new("gemini", "first_buy_ingredient", "gemini::first_buy_ingredient()"),
    StdlibFunctionRegistration::new("gemini", "first_query", "gemini::first_query()"),
    StdlibFunctionRegistration::new("gemini", "first_query_bag", "gemini::first_query_bag()"),
    StdlibFunctionRegistration::new("gemini", "first_upgrade", "gemini::first_upgrade(spirit_id: int, catch_time: int)"),
    StdlibFunctionRegistration::new("gemini", "first_upgrade_to_100", "gemini::first_upgrade_to_100(spirit_id: int, catch_time: int)"),
    StdlibFunctionRegistration::new("gemini", "second_add_score", "gemini::second_add_score(kind: int, score: int)"),
    StdlibFunctionRegistration::new("gemini", "second_buy", "gemini::second_buy()"),
    StdlibFunctionRegistration::new("gemini", "second_claim_gift", "gemini::second_claim_gift()"),
    StdlibFunctionRegistration::new("gemini", "second_query", "gemini::second_query()"),
    StdlibFunctionRegistration::new("gemini", "submit_second", "gemini::submit_second(kind: int)"),
    StdlibFunctionRegistration::new("gemini", "submit_third", "gemini::submit_third(spirit_id: int, catch_time: int)"),
    StdlibFunctionRegistration::new("gemini", "submit_third_combat", "gemini::submit_third_combat(side: int, index: int)"),
    StdlibFunctionRegistration::new("gemini", "submit_third_without_spirit", "gemini::submit_third_without_spirit()"),
    StdlibFunctionRegistration::new("gemini", "third_buy_challenge_count", "gemini::third_buy_challenge_count()"),
    StdlibFunctionRegistration::new("gemini", "third_buy_level", "gemini::third_buy_level(spirit_id: int, catch_time: int)"),
    StdlibFunctionRegistration::new("gemini", "third_buy_score", "gemini::third_buy_score()"),
    StdlibFunctionRegistration::new("gemini", "third_buy_score_by_index", "gemini::third_buy_score_by_index(side: int, index: int, score: int)"),
    StdlibFunctionRegistration::new("gemini", "third_query", "gemini::third_query()"),
    StdlibFunctionRegistration::new("gemini", "third_query_bag", "gemini::third_query_bag()"),
    StdlibFunctionRegistration::new("home", "enter", "home::enter()"),
    StdlibFunctionRegistration::new("home", "get_friend_list", "home::get_friend_list()"),
    StdlibFunctionRegistration::new("home", "get_friend_overview", "home::get_friend_overview(friend_uin: int, area_id: int)"),
    StdlibFunctionRegistration::new("home", "get_overview", "home::get_overview(area_id: int)"),
    StdlibFunctionRegistration::new("home", "get_training_spirit_report", "home::get_training_spirit_report(spirit_id: int, catch_time: int)"),
    StdlibFunctionRegistration::new("home", "get_training_spirits", "home::get_training_spirits()"),
    StdlibFunctionRegistration::new("home", "visit_friend", "home::visit_friend(friend_uin: int)"),
    StdlibFunctionRegistration::new("home", "query_coach_spirits", "home::query_coach_spirits(refresh: bool)"),
    StdlibFunctionRegistration::new("home", "take_training_spirit", "home::take_training_spirit(spirit_id: int, catch_time: int)"),
    StdlibFunctionRegistration::new("ice_crystal", "charge_with_item", "ice_crystal::charge_with_item(item: int)"),
    StdlibFunctionRegistration::new("ice_crystal", "condense_crystal", "ice_crystal::condense_crystal(crystal: int)"),
    StdlibFunctionRegistration::new("ice_crystal", "evolve", "ice_crystal::evolve(target: int, catch_time: int)"),
    StdlibFunctionRegistration::new("ice_crystal", "one_key_evolve", "ice_crystal::one_key_evolve(target: int, catch_time: int)"),
    StdlibFunctionRegistration::new("ice_crystal", "query", "ice_crystal::query()"),
    StdlibFunctionRegistration::new("ice_crystal", "query_evolution_bag", "ice_crystal::query_evolution_bag(target: int)"),
    StdlibFunctionRegistration::new("ice_crystal", "submit", "ice_crystal::submit()"),
    StdlibFunctionRegistration::new("incubative_machine", "claim_spirit", "incubative_machine::claim_spirit(which: int)"),
    StdlibFunctionRegistration::new("incubative_machine", "query_egg_list", "incubative_machine::query_egg_list(egg_type: int, page_index: int)"),
    StdlibFunctionRegistration::new("incubative_machine", "query_info", "incubative_machine::query_info(which: int)"),
    StdlibFunctionRegistration::new("incubative_machine", "set_complete_guide", "incubative_machine::set_complete_guide()"),
    StdlibFunctionRegistration::new("incubative_machine", "start", "incubative_machine::start(which: int, egg_type: int, egg_id: int, catch_time: int, egg_uin: int)"),
    StdlibFunctionRegistration::new("incubative_machine", "teach", "incubative_machine::teach(which: int)"),
    StdlibFunctionRegistration::new("incubative_machine", "terminate", "incubative_machine::terminate(which: int)"),
    StdlibFunctionRegistration::new("incubative_machine", "vip_speed_up", "incubative_machine::vip_speed_up(which: int)"),
    StdlibFunctionRegistration::new("jump_machine", "play", "jump_machine::play()"),
    StdlibFunctionRegistration::new("jump_machine", "query", "jump_machine::query()"),
    StdlibFunctionRegistration::new("king_fight", "cancel_match", "king_fight::cancel_match()"),
    StdlibFunctionRegistration::new("ladder", "cancel_match", "ladder::cancel_match()"),
    StdlibFunctionRegistration::new("ladder", "query_info", "ladder::query_info()"),
    StdlibFunctionRegistration::new("ladder", "query_rank", "ladder::query_rank()"),
    StdlibFunctionRegistration::new("ladder", "recover_spirits", "ladder::recover_spirits()"),
    StdlibFunctionRegistration::new("ladder", "try_recover_spirits", "ladder::try_recover_spirits()"),
    StdlibFunctionRegistration::new("leo", "first_buy_tail", "leo::first_buy_tail(count: int)"),
    StdlibFunctionRegistration::new("leo", "first_buy_wish", "leo::first_buy_wish()"),
    StdlibFunctionRegistration::new("leo", "first_exchange_item", "leo::first_exchange_item(exchange_position: int)"),
    StdlibFunctionRegistration::new("leo", "first_exchange_spirit", "leo::first_exchange_spirit()"),
    StdlibFunctionRegistration::new("leo", "first_query_status", "leo::first_query_status()"),
    StdlibFunctionRegistration::new("leo", "second_buy_full_level", "leo::second_buy_full_level(spirit_id: int, catch_time: int)"),
    StdlibFunctionRegistration::new("leo", "second_query", "leo::second_query()"),
    StdlibFunctionRegistration::new("leo", "second_query_spirit", "leo::second_query_spirit()"),
    StdlibFunctionRegistration::new("leo", "submit_second_combat", "leo::submit_second_combat(hunt_index: int)"),
    StdlibFunctionRegistration::new("leo", "submit_second_one_key", "leo::submit_second_one_key()"),
    StdlibFunctionRegistration::new("leo", "submit_second_spirit", "leo::submit_second_spirit(spirit_id: int, catch_time: int)"),
    StdlibFunctionRegistration::new("leo", "submit_third", "leo::submit_third(challenge_index: int, win: bool)"),
    StdlibFunctionRegistration::new("leo", "third_claim_reward", "leo::third_claim_reward()"),
    StdlibFunctionRegistration::new("leo", "third_evolve", "leo::third_evolve(catch_time: int)"),
    StdlibFunctionRegistration::new("leo", "third_full_level", "leo::third_full_level()"),
    StdlibFunctionRegistration::new("leo", "third_light_star", "leo::third_light_star(star_index: int)"),
    StdlibFunctionRegistration::new("leo", "third_query", "leo::third_query()"),
    StdlibFunctionRegistration::new("leo", "third_query_bag", "leo::third_query_bag()"),
    StdlibFunctionRegistration::new("libra", "first_advance", "libra::first_advance(spirit_id: int, catch_time: int)"),
    StdlibFunctionRegistration::new("libra", "first_claim_gift", "libra::first_claim_gift()"),
    StdlibFunctionRegistration::new("libra", "first_notify_full_level", "libra::first_notify_full_level(spirit_id: int, catch_time: int)"),
    StdlibFunctionRegistration::new("libra", "first_query", "libra::first_query()"),
    StdlibFunctionRegistration::new("libra", "first_query_bag", "libra::first_query_bag()"),
    StdlibFunctionRegistration::new("libra", "second_awaken", "libra::second_awaken()"),
    StdlibFunctionRegistration::new("libra", "second_buy_challenge_count", "libra::second_buy_challenge_count()"),
    StdlibFunctionRegistration::new("libra", "second_evolution", "libra::second_evolution(spirit_id: int, catch_time: int)"),
    StdlibFunctionRegistration::new("libra", "second_full_level", "libra::second_full_level(spirit_id: int, catch_time: int)"),
    StdlibFunctionRegistration::new("libra", "second_query", "libra::second_query()"),
    StdlibFunctionRegistration::new("libra", "second_query_bag", "libra::second_query_bag()"),
    StdlibFunctionRegistration::new("libra", "submit_first_combat", "libra::submit_first_combat(prop_index: int)"),
    StdlibFunctionRegistration::new("libra", "submit_first_game", "libra::submit_first_game()"),
    StdlibFunctionRegistration::new("libra", "submit_second", "libra::submit_second(npc_index: int)"),
    StdlibFunctionRegistration::new("libra", "third_buy_tail", "libra::third_buy_tail(count: int)"),
    StdlibFunctionRegistration::new("libra", "third_buy_wish", "libra::third_buy_wish()"),
    StdlibFunctionRegistration::new("libra", "third_exchange_item", "libra::third_exchange_item(exchange_position: int)"),
    StdlibFunctionRegistration::new("libra", "third_exchange_spirit", "libra::third_exchange_spirit()"),
    StdlibFunctionRegistration::new("libra", "third_query_status", "libra::third_query_status()"),
    StdlibFunctionRegistration::new("lookup", "guardian_pet_property_info", "lookup::guardian_pet_property_info(level: int)"),
    StdlibFunctionRegistration::new("lookup", "item_info", "lookup::item_info(item_id: int)"),
    StdlibFunctionRegistration::new("lookup", "item_infos", "lookup::item_infos(item_ids: array)"),
    StdlibFunctionRegistration::new("lookup", "ladder_match_config", "lookup::ladder_match_config()"),
    StdlibFunctionRegistration::new("lookup", "list_feature_names", "lookup::list_feature_names()"),
    StdlibFunctionRegistration::new("lookup", "list_plugin_infos", "lookup::list_plugin_infos()"),
    StdlibFunctionRegistration::new("lookup", "list_spirit_book_entries", "lookup::list_spirit_book_entries(book_id: int)"),
    StdlibFunctionRegistration::new("lookup", "list_spirit_book_summaries", "lookup::list_spirit_book_summaries()"),
    StdlibFunctionRegistration::new("lookup", "list_strive_item_infos", "lookup::list_strive_item_infos()"),
    StdlibFunctionRegistration::new("lookup", "list_talent_infos", "lookup::list_talent_infos()"),
    StdlibFunctionRegistration::new("lookup", "magic_info", "lookup::magic_info(magic_id: int)"),
    StdlibFunctionRegistration::new("lookup", "plugin_info", "lookup::plugin_info(plugin_name: string)"),
    StdlibFunctionRegistration::new("lookup", "skill_info", "lookup::skill_info(skill_id: int)"),
    StdlibFunctionRegistration::new("lookup", "skill_infos", "lookup::skill_infos(skill_ids: array)"),
    StdlibFunctionRegistration::new("lookup", "spirit_book", "lookup::spirit_book(book_id: int)"),
    StdlibFunctionRegistration::new("lookup", "spirit_info", "lookup::spirit_info(spirit_id: int)"),
    StdlibFunctionRegistration::new("lookup", "spirit_infos", "lookup::spirit_infos(spirit_ids: array)"),
    StdlibFunctionRegistration::new("lookup", "strive_item_info", "lookup::strive_item_info(item_id: int)"),
    StdlibFunctionRegistration::new("lookup", "talent_info", "lookup::talent_info(talent_type: int)"),
    StdlibFunctionRegistration::new("lookup", "title_info", "lookup::title_info(title_id: int)"),
    StdlibFunctionRegistration::new("lookup", "try_spirit_info", "lookup::try_spirit_info(spirit_id: int)"),
    StdlibFunctionRegistration::new("magic_pioneer", "bat_prince_claim_gift", "magic_pioneer::bat_prince_claim_gift()"),
    StdlibFunctionRegistration::new("magic_pioneer", "bat_prince_one_key", "magic_pioneer::bat_prince_one_key()"),
    StdlibFunctionRegistration::new("magic_pioneer", "bat_prince_query", "magic_pioneer::bat_prince_query()"),
    StdlibFunctionRegistration::new("magic_pioneer", "bat_prince_start_indexed_combat", "magic_pioneer::bat_prince_start_indexed_combat(index: int)"),
    StdlibFunctionRegistration::new("magic_pioneer", "blue_water_beast_check", "magic_pioneer::blue_water_beast_check()"),
    StdlibFunctionRegistration::new("magic_pioneer", "blue_water_beast_claim_gift", "magic_pioneer::blue_water_beast_claim_gift()"),
    StdlibFunctionRegistration::new("magic_pioneer", "blue_water_beast_one_key", "magic_pioneer::blue_water_beast_one_key()"),
    StdlibFunctionRegistration::new("magic_pioneer", "blue_water_beast_query", "magic_pioneer::blue_water_beast_query()"),
    StdlibFunctionRegistration::new("magic_pioneer", "dark_pioneer_dragon_add", "magic_pioneer::dark_pioneer_dragon_add()"),
    StdlibFunctionRegistration::new("magic_pioneer", "dark_pioneer_dragon_buy", "magic_pioneer::dark_pioneer_dragon_buy()"),
    StdlibFunctionRegistration::new("magic_pioneer", "dark_pioneer_dragon_claim_reward", "magic_pioneer::dark_pioneer_dragon_claim_reward()"),
    StdlibFunctionRegistration::new("magic_pioneer", "dark_pioneer_dragon_query", "magic_pioneer::dark_pioneer_dragon_query()"),
    StdlibFunctionRegistration::new("magic_pioneer", "drill_man_claim_gift", "magic_pioneer::drill_man_claim_gift()"),
    StdlibFunctionRegistration::new("magic_pioneer", "drill_man_one_key", "magic_pioneer::drill_man_one_key()"),
    StdlibFunctionRegistration::new("magic_pioneer", "drill_man_query", "magic_pioneer::drill_man_query()"),
    StdlibFunctionRegistration::new("magic_pioneer", "drill_man_start_combat", "magic_pioneer::drill_man_start_combat()"),
    StdlibFunctionRegistration::new("magic_pioneer", "golden_mantis_buy", "magic_pioneer::golden_mantis_buy()"),
    StdlibFunctionRegistration::new("magic_pioneer", "golden_mantis_claim_gift", "magic_pioneer::golden_mantis_claim_gift()"),
    StdlibFunctionRegistration::new("magic_pioneer", "golden_mantis_query", "magic_pioneer::golden_mantis_query()"),
    StdlibFunctionRegistration::new("magic_pioneer", "golden_mantis_start_combat", "magic_pioneer::golden_mantis_start_combat()"),
    StdlibFunctionRegistration::new("magic_pioneer", "ice_crystal_tiger_claim_gift", "magic_pioneer::ice_crystal_tiger_claim_gift()"),
    StdlibFunctionRegistration::new("magic_pioneer", "ice_crystal_tiger_one_key", "magic_pioneer::ice_crystal_tiger_one_key()"),
    StdlibFunctionRegistration::new("magic_pioneer", "ice_crystal_tiger_query", "magic_pioneer::ice_crystal_tiger_query()"),
    StdlibFunctionRegistration::new("magic_pioneer", "ice_crystal_tiger_start_indexed_combat", "magic_pioneer::ice_crystal_tiger_start_indexed_combat(index: int)"),
    StdlibFunctionRegistration::new("magic_pioneer", "little_angel_angie_buy", "magic_pioneer::little_angel_angie_buy()"),
    StdlibFunctionRegistration::new("magic_pioneer", "little_angel_angie_claim_reward", "magic_pioneer::little_angel_angie_claim_reward()"),
    StdlibFunctionRegistration::new("magic_pioneer", "little_angel_angie_query", "magic_pioneer::little_angel_angie_query()"),
    StdlibFunctionRegistration::new("magic_pioneer", "loki_add", "magic_pioneer::loki_add()"),
    StdlibFunctionRegistration::new("magic_pioneer", "loki_buy", "magic_pioneer::loki_buy()"),
    StdlibFunctionRegistration::new("magic_pioneer", "loki_claim_gift", "magic_pioneer::loki_claim_gift()"),
    StdlibFunctionRegistration::new("magic_pioneer", "loki_query", "magic_pioneer::loki_query()"),
    StdlibFunctionRegistration::new("magic_pioneer", "loki_query_all", "magic_pioneer::loki_query_all()"),
    StdlibFunctionRegistration::new("magic_pioneer", "magic_tail_cat_buy", "magic_pioneer::magic_tail_cat_buy()"),
    StdlibFunctionRegistration::new("magic_pioneer", "magic_tail_cat_claim_gift", "magic_pioneer::magic_tail_cat_claim_gift()"),
    StdlibFunctionRegistration::new("magic_pioneer", "magic_tail_cat_learn", "magic_pioneer::magic_tail_cat_learn()"),
    StdlibFunctionRegistration::new("magic_pioneer", "magic_tail_cat_query", "magic_pioneer::magic_tail_cat_query()"),
    StdlibFunctionRegistration::new("magic_pioneer", "magic_tail_cat_start_combat", "magic_pioneer::magic_tail_cat_start_combat()"),
    StdlibFunctionRegistration::new("magic_pioneer", "nether_fox_buy", "magic_pioneer::nether_fox_buy()"),
    StdlibFunctionRegistration::new("magic_pioneer", "nether_fox_claim_gift", "magic_pioneer::nether_fox_claim_gift()"),
    StdlibFunctionRegistration::new("magic_pioneer", "nether_fox_query", "magic_pioneer::nether_fox_query()"),
    StdlibFunctionRegistration::new("magic_pioneer", "nether_fox_start_combat", "magic_pioneer::nether_fox_start_combat(index: int)"),
    StdlibFunctionRegistration::new("magic_pioneer", "red_lotus_beast_buy", "magic_pioneer::red_lotus_beast_buy()"),
    StdlibFunctionRegistration::new("magic_pioneer", "red_lotus_beast_claim_gift", "magic_pioneer::red_lotus_beast_claim_gift()"),
    StdlibFunctionRegistration::new("magic_pioneer", "red_lotus_beast_query", "magic_pioneer::red_lotus_beast_query()"),
    StdlibFunctionRegistration::new("magic_pioneer", "red_lotus_beast_start_combat", "magic_pioneer::red_lotus_beast_start_combat(index: int)"),
    StdlibFunctionRegistration::new("magic_pioneer", "rock_armor_lord_add", "magic_pioneer::rock_armor_lord_add()"),
    StdlibFunctionRegistration::new("magic_pioneer", "rock_armor_lord_buy", "magic_pioneer::rock_armor_lord_buy()"),
    StdlibFunctionRegistration::new("magic_pioneer", "rock_armor_lord_claim_reward", "magic_pioneer::rock_armor_lord_claim_reward()"),
    StdlibFunctionRegistration::new("magic_pioneer", "rock_armor_lord_query", "magic_pioneer::rock_armor_lord_query()"),
    StdlibFunctionRegistration::new("magic_pioneer", "submit_bat_prince", "magic_pioneer::submit_bat_prince()"),
    StdlibFunctionRegistration::new("magic_pioneer", "submit_blue_water_beast_combat", "magic_pioneer::submit_blue_water_beast_combat(index: int)"),
    StdlibFunctionRegistration::new("magic_pioneer", "submit_blue_water_beast_game", "magic_pioneer::submit_blue_water_beast_game()"),
    StdlibFunctionRegistration::new("magic_pioneer", "submit_dark_pioneer_dragon", "magic_pioneer::submit_dark_pioneer_dragon()"),
    StdlibFunctionRegistration::new("magic_pioneer", "submit_drill_man", "magic_pioneer::submit_drill_man(index: int, success: int)"),
    StdlibFunctionRegistration::new("magic_pioneer", "submit_drill_man_combat", "magic_pioneer::submit_drill_man_combat()"),
    StdlibFunctionRegistration::new("magic_pioneer", "submit_golden_mantis", "magic_pioneer::submit_golden_mantis(index: int)"),
    StdlibFunctionRegistration::new("magic_pioneer", "submit_golden_mantis_combat", "magic_pioneer::submit_golden_mantis_combat()"),
    StdlibFunctionRegistration::new("magic_pioneer", "submit_ice_crystal_tiger_chain", "magic_pioneer::submit_ice_crystal_tiger_chain(index: int, number: int)"),
    StdlibFunctionRegistration::new("magic_pioneer", "submit_ice_crystal_tiger_combat", "magic_pioneer::submit_ice_crystal_tiger_combat()"),
    StdlibFunctionRegistration::new("magic_pioneer", "submit_ice_crystal_tiger_game", "magic_pioneer::submit_ice_crystal_tiger_game()"),
    StdlibFunctionRegistration::new("magic_pioneer", "submit_little_angel_angie", "magic_pioneer::submit_little_angel_angie(index: int)"),
    StdlibFunctionRegistration::new("magic_pioneer", "submit_loki", "magic_pioneer::submit_loki()"),
    StdlibFunctionRegistration::new("magic_pioneer", "submit_magic_tail_cat", "magic_pioneer::submit_magic_tail_cat()"),
    StdlibFunctionRegistration::new("magic_pioneer", "submit_magic_tail_cat_combat", "magic_pioneer::submit_magic_tail_cat_combat()"),
    StdlibFunctionRegistration::new("magic_pioneer", "submit_nether_fox", "magic_pioneer::submit_nether_fox(number: int)"),
    StdlibFunctionRegistration::new("magic_pioneer", "submit_nether_fox_combat", "magic_pioneer::submit_nether_fox_combat()"),
    StdlibFunctionRegistration::new("magic_pioneer", "submit_red_lotus_beast", "magic_pioneer::submit_red_lotus_beast()"),
    StdlibFunctionRegistration::new("magic_pioneer", "submit_red_lotus_beast_combat", "magic_pioneer::submit_red_lotus_beast_combat()"),
    StdlibFunctionRegistration::new("magic_pioneer", "submit_rock_armor_lord", "magic_pioneer::submit_rock_armor_lord(index: int, success: int)"),
    StdlibFunctionRegistration::new("magic_pioneer", "submit_vanguard_lord", "magic_pioneer::submit_vanguard_lord()"),
    StdlibFunctionRegistration::new("magic_pioneer", "vanguard_lord_buy", "magic_pioneer::vanguard_lord_buy()"),
    StdlibFunctionRegistration::new("magic_pioneer", "vanguard_lord_claim_reward", "magic_pioneer::vanguard_lord_claim_reward()"),
    StdlibFunctionRegistration::new("magic_pioneer", "vanguard_lord_complete", "magic_pioneer::vanguard_lord_complete()"),
    StdlibFunctionRegistration::new("magic_pioneer", "vanguard_lord_exchange", "magic_pioneer::vanguard_lord_exchange(index: int, num: int)"),
    StdlibFunctionRegistration::new("magic_pioneer", "vanguard_lord_put", "magic_pioneer::vanguard_lord_put()"),
    StdlibFunctionRegistration::new("magic_pioneer", "vanguard_lord_query", "magic_pioneer::vanguard_lord_query()"),
    StdlibFunctionRegistration::new("manor", "apply_coco_tree_feed", "manor::apply_coco_tree_feed(feed_type: int)"),
    StdlibFunctionRegistration::new("manor", "apply_friend_coco_tree_feed", "manor::apply_friend_coco_tree_feed(friend_uin: int)"),
    StdlibFunctionRegistration::new("manor", "claim_strawman_gift", "manor::claim_strawman_gift()"),
    StdlibFunctionRegistration::new("manor", "claim_strawman_reward", "manor::claim_strawman_reward()"),
    StdlibFunctionRegistration::new("manor", "get_friend_list", "manor::get_friend_list(version: int)"),
    StdlibFunctionRegistration::new("manor", "get_friend_ground_info", "manor::get_friend_ground_info(friend_uin: int)"),
    StdlibFunctionRegistration::new("manor", "get_friend_plant_status", "manor::get_friend_plant_status(friend_uin: int)"),
    StdlibFunctionRegistration::new("manor", "get_ground_info", "manor::get_ground_info()"),
    StdlibFunctionRegistration::new("manor", "get_plant_status", "manor::get_plant_status()"),
    StdlibFunctionRegistration::new("manor", "get_seed_bag", "manor::get_seed_bag()"),
    StdlibFunctionRegistration::new("manor", "enter", "manor::enter()"),
    StdlibFunctionRegistration::new("manor", "visit_friend", "manor::visit_friend(friend_uin: int)"),
    StdlibFunctionRegistration::new("manor", "query_coco_tree", "manor::query_coco_tree()"),
    StdlibFunctionRegistration::new("manor", "query_friend_coco_tree", "manor::query_friend_coco_tree(friend_uin: int)"),
    StdlibFunctionRegistration::new("manor", "reap", "manor::reap(ground_id: int)"),
    StdlibFunctionRegistration::new("manor", "reclaim", "manor::reclaim(ground_id: int)"),
    StdlibFunctionRegistration::new("manor", "sow", "manor::sow(seed_id: int, ground_id: int)"),
    StdlibFunctionRegistration::new("manor", "submit_strawman_result", "manor::submit_strawman_result(game_result: int)"),
    StdlibFunctionRegistration::new("manor", "uproot", "manor::uproot(ground_id: int)"),
    StdlibFunctionRegistration::new("manor", "use_fertilizer", "manor::use_fertilizer(ground_id: int, fertilizer_item_id: int)"),
    StdlibFunctionRegistration::new("manor", "weed", "manor::weed(ground_id: int, weed_type: int)"),
    StdlibFunctionRegistration::new("memory", "daily_clear", "memory::daily_clear()"),
    StdlibFunctionRegistration::new("memory", "daily_combat_limit", "memory::daily_combat_limit()"),
    StdlibFunctionRegistration::new("memory", "daily_combat_limit_message", "memory::daily_combat_limit_message()"),
    StdlibFunctionRegistration::new("memory", "daily_combat_limit_reached", "memory::daily_combat_limit_reached()"),
    StdlibFunctionRegistration::new("memory", "daily_combat_limit_return_code", "memory::daily_combat_limit_return_code()"),
    StdlibFunctionRegistration::new("memory", "daily_combat_observed_completed", "memory::daily_combat_observed_completed()"),
    StdlibFunctionRegistration::new("memory", "daily_combat_observed_started", "memory::daily_combat_observed_started()"),
    StdlibFunctionRegistration::new("memory", "daily_combat_tracking_since", "memory::daily_combat_tracking_since()"),
    StdlibFunctionRegistration::new("memory", "daily_delete", "memory::daily_delete(key: string)"),
    StdlibFunctionRegistration::new("memory", "daily_get_bool", "memory::daily_get_bool(key: string, default_value: bool)"),
    StdlibFunctionRegistration::new("memory", "daily_get_int", "memory::daily_get_int(key: string, default_value: int)"),
    StdlibFunctionRegistration::new("memory", "daily_get_string", "memory::daily_get_string(key: string, default_value: string)"),
    StdlibFunctionRegistration::new("memory", "daily_increment_int", "memory::daily_increment_int(key: string, delta: int)"),
    StdlibFunctionRegistration::new("memory", "daily_list_keys", "memory::daily_list_keys()"),
    StdlibFunctionRegistration::new("memory", "daily_set_bool", "memory::daily_set_bool(key: string, value: bool)"),
    StdlibFunctionRegistration::new("memory", "daily_set_int", "memory::daily_set_int(key: string, value: int)"),
    StdlibFunctionRegistration::new("memory", "daily_set_string", "memory::daily_set_string(key: string, value: string)"),
    StdlibFunctionRegistration::new("memory", "today", "memory::today()"),
    StdlibFunctionRegistration::new("mountain_sea", "enter_boss", "mountain_sea::enter_boss(boss_index: int)"),
    StdlibFunctionRegistration::new("mountain_sea", "open", "mountain_sea::open()"),
    StdlibFunctionRegistration::new("mountain_sea", "query", "mountain_sea::query()"),
    StdlibFunctionRegistration::new("mountain_sea", "submit", "mountain_sea::submit()"),
    StdlibFunctionRegistration::new("mountain_sea", "summon", "mountain_sea::summon(page_index: int, soul_type: int, soul_count: int)"),
    StdlibFunctionRegistration::new("multi_evolution", "fire_claim_reward", "multi_evolution::fire_claim_reward()"),
    StdlibFunctionRegistration::new("multi_evolution", "fire_evolve", "multi_evolution::fire_evolve(target_index: int, spirit_id: int, catch_time: int, item_count: int, fire_score: int)"),
    StdlibFunctionRegistration::new("multi_evolution", "fire_query_booster_item_count", "multi_evolution::fire_query_booster_item_count()"),
    StdlibFunctionRegistration::new("multi_evolution", "fire_query_candidates", "multi_evolution::fire_query_candidates(target_index: int)"),
    StdlibFunctionRegistration::new("multi_evolution", "fire_query_reward_available", "multi_evolution::fire_query_reward_available()"),
    StdlibFunctionRegistration::new("multi_evolution", "grass_first_evolve", "multi_evolution::grass_first_evolve(target_index: int, spirit_id: int, catch_time: int, sunlight: int)"),
    StdlibFunctionRegistration::new("multi_evolution", "grass_query_candidates", "multi_evolution::grass_query_candidates(target_index: int)"),
    StdlibFunctionRegistration::new("multi_evolution", "grass_second_evolve", "multi_evolution::grass_second_evolve(target_index: int, spirit_id: int, catch_time: int, sunlight: int)"),
    StdlibFunctionRegistration::new("multi_evolution", "water_evolve", "multi_evolution::water_evolve(target_index: int, spirit_id: int, catch_time: int)"),
    StdlibFunctionRegistration::new("multi_evolution", "water_query_candidates", "multi_evolution::water_query_candidates(target_index: int)"),
    StdlibFunctionRegistration::new("mystery_fusion", "claim_reward", "mystery_fusion::claim_reward()"),
    StdlibFunctionRegistration::new("mystery_fusion", "fuse", "mystery_fusion::fuse(recipe_index: int, material_bag_indexes: array, personality: int)"),
    StdlibFunctionRegistration::new("mystery_fusion", "prepare_combat", "mystery_fusion::prepare_combat(battle_index: int)"),
    StdlibFunctionRegistration::new("mystery_fusion", "query", "mystery_fusion::query()"),
    StdlibFunctionRegistration::new("mystery_fusion", "query_material_bag", "mystery_fusion::query_material_bag(spirit_id: int)"),
    StdlibFunctionRegistration::new("mystery_fusion", "submit", "mystery_fusion::submit()"),
    StdlibFunctionRegistration::new("news", "list_active_config_items", "news::list_active_config_items()"),
    StdlibFunctionRegistration::new("news", "query_active_ids", "news::query_active_ids()"),
    StdlibFunctionRegistration::new("news", "query_active_items", "news::query_active_items()"),
    StdlibFunctionRegistration::new("news", "query_reports", "news::query_reports()"),
    StdlibFunctionRegistration::new("personality", "name", "personality::name(personality: int)"),
    StdlibFunctionRegistration::new("personality", "names", "personality::names()"),
    StdlibFunctionRegistration::new("pet_egg", "cancel", "pet_egg::cancel()"),
    StdlibFunctionRegistration::new("pet_egg", "preview", "pet_egg::preview(male_index: int, female_index: int)"),
    StdlibFunctionRegistration::new("pet_egg", "query_info", "pet_egg::query_info()"),
    StdlibFunctionRegistration::new("pet_egg", "start", "pet_egg::start(male_index: int, female_index: int)"),
    StdlibFunctionRegistration::new("pet_egg", "vip_speed_up", "pet_egg::vip_speed_up()"),
    StdlibFunctionRegistration::new("pet_training", "query", "pet_training::query(training_type: int)"),
    StdlibFunctionRegistration::new("pet_training", "submit", "pet_training::submit(training_type: int, pet_id: int)"),
    StdlibFunctionRegistration::new("pisces", "first_buy", "pisces::first_buy()"),
    StdlibFunctionRegistration::new("pisces", "first_claim_gift", "pisces::first_claim_gift()"),
    StdlibFunctionRegistration::new("pisces", "first_exchange", "pisces::first_exchange()"),
    StdlibFunctionRegistration::new("pisces", "first_query", "pisces::first_query()"),
    StdlibFunctionRegistration::new("pisces", "second_claim_gift", "pisces::second_claim_gift(spirit_id: int, catch_time: int)"),
    StdlibFunctionRegistration::new("pisces", "second_evolution", "pisces::second_evolution(spirit_id: int, catch_time: int)"),
    StdlibFunctionRegistration::new("pisces", "second_query", "pisces::second_query()"),
    StdlibFunctionRegistration::new("pisces", "second_repair", "pisces::second_repair(repair_index: int)"),
    StdlibFunctionRegistration::new("pisces", "second_view", "pisces::second_view(kind: int)"),
    StdlibFunctionRegistration::new("pisces", "submit_first", "pisces::submit_first()"),
    StdlibFunctionRegistration::new("pisces", "submit_second", "pisces::submit_second(spirit_id: int, catch_time: int)"),
    StdlibFunctionRegistration::new("pisces", "submit_second_combat", "pisces::submit_second_combat(combat_index: int)"),
    StdlibFunctionRegistration::new("pisces", "submit_second_without_spirit", "pisces::submit_second_without_spirit()"),
    StdlibFunctionRegistration::new("pisces", "submit_third", "pisces::submit_third(boss_index: int)"),
    StdlibFunctionRegistration::new("pisces", "third_buy", "pisces::third_buy(kind: int, spirit_id: int, catch_time: int)"),
    StdlibFunctionRegistration::new("pisces", "third_complete", "pisces::third_complete(level_index: int)"),
    StdlibFunctionRegistration::new("pisces", "third_full_level", "pisces::third_full_level(spirit_id: int, catch_time: int)"),
    StdlibFunctionRegistration::new("pisces", "third_get_item", "pisces::third_get_item(reward_index: int)"),
    StdlibFunctionRegistration::new("pisces", "third_query", "pisces::third_query()"),
    StdlibFunctionRegistration::new("pisces", "third_query_bag", "pisces::third_query_bag(kind: int)"),
    StdlibFunctionRegistration::new("pisces", "third_up", "pisces::third_up(spirit_id: int, catch_time: int)"),
    StdlibFunctionRegistration::new("pk", "accept", "pk::accept()"),
    StdlibFunctionRegistration::new("pk", "cancel_waiting", "pk::cancel_waiting()"),
    StdlibFunctionRegistration::new("pk", "invite", "pk::invite(target_uin: int)"),
    StdlibFunctionRegistration::new("pk", "reject", "pk::reject()"),
    StdlibFunctionRegistration::new("play_guide", "diamond_task_claim_reward", "play_guide::diamond_task_claim_reward(index: int)"),
    StdlibFunctionRegistration::new("play_guide", "diamond_task_query", "play_guide::diamond_task_query()"),
    StdlibFunctionRegistration::new("play_guide", "qq_game_hall_gift", "play_guide::qq_game_hall_gift()"),
    StdlibFunctionRegistration::new("play_guide", "week_task_claim_task", "play_guide::week_task_claim_task(index: int)"),
    StdlibFunctionRegistration::new("play_guide", "week_task_exchange", "play_guide::week_task_exchange(exchange_type: int, index: int)"),
    StdlibFunctionRegistration::new("play_guide", "week_task_query", "play_guide::week_task_query()"),
    StdlibFunctionRegistration::new("profile", "get_user_info", "profile::get_user_info()"),
    StdlibFunctionRegistration::new("profile", "is_in_combat", "profile::is_in_combat()"),
    StdlibFunctionRegistration::new("profile", "query_server_time", "profile::query_server_time()"),
    StdlibFunctionRegistration::new("profile", "try_query_server_time", "profile::try_query_server_time()"),
    StdlibFunctionRegistration::new("reclaim_goods", "query_eggs", "reclaim_goods::query_eggs()"),
    StdlibFunctionRegistration::new("reclaim_goods", "query_goods", "reclaim_goods::query_goods(goods_type: int)"),
    StdlibFunctionRegistration::new("reclaim_goods", "query_prices", "reclaim_goods::query_prices(goods_type: int)"),
    StdlibFunctionRegistration::new("reclaim_goods", "sell_egg", "reclaim_goods::sell_egg(host_uin: int, spirit_id: int, catch_time: int)"),
    StdlibFunctionRegistration::new("reclaim_goods", "sell_eggs_batch", "reclaim_goods::sell_eggs_batch(eggs: array)"),
    StdlibFunctionRegistration::new("reclaim_goods", "sell_goods", "reclaim_goods::sell_goods(goods_type: int, item_id: int, count: int)"),
    StdlibFunctionRegistration::new("reclaim_goods", "sell_goods_batch", "reclaim_goods::sell_goods_batch(goods_type: int, items: array)"),
    StdlibFunctionRegistration::new("remote_state", "load_npc_value", "remote_state::load_npc_value(npc_id: int)"),
    StdlibFunctionRegistration::new("remote_state", "load_scene_data", "remote_state::load_scene_data(scene_id: int)"),
    StdlibFunctionRegistration::new("remote_state", "update_npc_value", "remote_state::update_npc_value(npc_id: int, value: int)"),
    StdlibFunctionRegistration::new("remote_state", "update_scene_data", "remote_state::update_scene_data(scene_id: int, values: blob)"),
    StdlibFunctionRegistration::new("role", "get_cached_scene_roles", "role::get_cached_scene_roles()"),
    StdlibFunctionRegistration::new("role", "try_change_avatar", "role::try_change_avatar(avatar: array)"),
    StdlibFunctionRegistration::new("role", "try_change_avatar_slot", "role::try_change_avatar_slot(avatar_position: int, avatar_id: int)"),
    StdlibFunctionRegistration::new("sagittarius", "first_add_map", "sagittarius::first_add_map()"),
    StdlibFunctionRegistration::new("sagittarius", "first_add_speed", "sagittarius::first_add_speed()"),
    StdlibFunctionRegistration::new("sagittarius", "first_claim_spirit", "sagittarius::first_claim_spirit()"),
    StdlibFunctionRegistration::new("sagittarius", "first_complete", "sagittarius::first_complete(index: int)"),
    StdlibFunctionRegistration::new("sagittarius", "first_pick_shine", "sagittarius::first_pick_shine()"),
    StdlibFunctionRegistration::new("sagittarius", "first_query", "sagittarius::first_query()"),
    StdlibFunctionRegistration::new("sagittarius", "first_query_scene", "sagittarius::first_query_scene()"),
    StdlibFunctionRegistration::new("sagittarius", "first_show_map", "sagittarius::first_show_map()"),
    StdlibFunctionRegistration::new("sagittarius", "second_buy_up", "sagittarius::second_buy_up(spirit_id: int, catch_time: int)"),
    StdlibFunctionRegistration::new("sagittarius", "second_level_up", "sagittarius::second_level_up(spirit_id: int, catch_time: int)"),
    StdlibFunctionRegistration::new("sagittarius", "second_query", "sagittarius::second_query()"),
    StdlibFunctionRegistration::new("sagittarius", "second_query_bag", "sagittarius::second_query_bag(bag_type: int)"),
    StdlibFunctionRegistration::new("sagittarius", "second_random", "sagittarius::second_random()"),
    StdlibFunctionRegistration::new("sagittarius", "second_spirit_up", "sagittarius::second_spirit_up(spirit_id: int, catch_time: int)"),
    StdlibFunctionRegistration::new("sagittarius", "second_start", "sagittarius::second_start()"),
    StdlibFunctionRegistration::new("sagittarius", "second_task", "sagittarius::second_task(task_type: int)"),
    StdlibFunctionRegistration::new("sagittarius", "submit_first", "sagittarius::submit_first()"),
    StdlibFunctionRegistration::new("sagittarius", "submit_third", "sagittarius::submit_third(boss_index: int)"),
    StdlibFunctionRegistration::new("sagittarius", "third_add_challenge_count", "sagittarius::third_add_challenge_count()"),
    StdlibFunctionRegistration::new("sagittarius", "third_buy_evolve", "sagittarius::third_buy_evolve(spirit_id: int, catch_time: int)"),
    StdlibFunctionRegistration::new("sagittarius", "third_buy_spirit", "sagittarius::third_buy_spirit()"),
    StdlibFunctionRegistration::new("sagittarius", "third_buy_star_num", "sagittarius::third_buy_star_num(score_index: int)"),
    StdlibFunctionRegistration::new("sagittarius", "third_query", "sagittarius::third_query()"),
    StdlibFunctionRegistration::new("sagittarius", "third_query_bag", "sagittarius::third_query_bag()"),
    StdlibFunctionRegistration::new("sagittarius", "third_up", "sagittarius::third_up(spirit_id: int, catch_time: int)"),
    StdlibFunctionRegistration::new("scene", "get_current_scene", "scene::get_current_scene()"),
    StdlibFunctionRegistration::new("scene", "get_scene_spirits", "scene::get_scene_spirits()"),
    StdlibFunctionRegistration::new("scene", "move_to_scene", "scene::move_to_scene(scene_id: int)"),
    StdlibFunctionRegistration::new("scene", "try_move_to_scene", "scene::try_move_to_scene(scene_id: int)"),
    StdlibFunctionRegistration::new("scorpio", "first_buy_direct", "scorpio::first_buy_direct()"),
    StdlibFunctionRegistration::new("scorpio", "first_evolve", "scorpio::first_evolve(spirit_id: int, catch_time: int)"),
    StdlibFunctionRegistration::new("scorpio", "first_level_up", "scorpio::first_level_up(spirit_id: int, catch_time: int)"),
    StdlibFunctionRegistration::new("scorpio", "first_query", "scorpio::first_query()"),
    StdlibFunctionRegistration::new("scorpio", "first_query_bag", "scorpio::first_query_bag()"),
    StdlibFunctionRegistration::new("scorpio", "second_buy_challenge_count", "scorpio::second_buy_challenge_count()"),
    StdlibFunctionRegistration::new("scorpio", "second_buy_direct", "scorpio::second_buy_direct()"),
    StdlibFunctionRegistration::new("scorpio", "second_evolve", "scorpio::second_evolve(spirit_id: int, catch_time: int)"),
    StdlibFunctionRegistration::new("scorpio", "second_level_up", "scorpio::second_level_up(spirit_id: int, catch_time: int)"),
    StdlibFunctionRegistration::new("scorpio", "second_query", "scorpio::second_query()"),
    StdlibFunctionRegistration::new("scorpio", "second_query_bag", "scorpio::second_query_bag()"),
    StdlibFunctionRegistration::new("scorpio", "submit_first_game", "scorpio::submit_first_game(score: int)"),
    StdlibFunctionRegistration::new("scorpio", "submit_second", "scorpio::submit_second(reward_source: int)"),
    StdlibFunctionRegistration::new("scorpio", "submit_third_game", "scorpio::submit_third_game(success: bool)"),
    StdlibFunctionRegistration::new("scorpio", "third_buy_guess_count", "scorpio::third_buy_guess_count(count: int)"),
    StdlibFunctionRegistration::new("scorpio", "third_buy_red_sand", "scorpio::third_buy_red_sand(count: int)"),
    StdlibFunctionRegistration::new("scorpio", "third_exchange_spirit", "scorpio::third_exchange_spirit()"),
    StdlibFunctionRegistration::new("scorpio", "third_query", "scorpio::third_query()"),
    StdlibFunctionRegistration::new("sentinel_intelligence", "claim_prize", "sentinel_intelligence::claim_prize(boss_index: int)"),
    StdlibFunctionRegistration::new("sentinel_intelligence", "evolve_spirit", "sentinel_intelligence::evolve_spirit(index: int, catch_time: int)"),
    StdlibFunctionRegistration::new("sentinel_intelligence", "exchange_item", "sentinel_intelligence::exchange_item(index: int)"),
    StdlibFunctionRegistration::new("sentinel_intelligence", "exchange_spirit", "sentinel_intelligence::exchange_spirit(index: int)"),
    StdlibFunctionRegistration::new("sentinel_intelligence", "query", "sentinel_intelligence::query()"),
    StdlibFunctionRegistration::new("sentinel_intelligence", "query_all", "sentinel_intelligence::query_all()"),
    StdlibFunctionRegistration::new("sentinel_intelligence", "query_bag", "sentinel_intelligence::query_bag(evolve_spirit_id: int)"),
    StdlibFunctionRegistration::new("sentinel_intelligence", "refresh_boss", "sentinel_intelligence::refresh_boss()"),
    StdlibFunctionRegistration::new("sentinel_intelligence", "refresh_exchange", "sentinel_intelligence::refresh_exchange()"),
    StdlibFunctionRegistration::new("sentinel_intelligence", "refresh_mission", "sentinel_intelligence::refresh_mission()"),
    StdlibFunctionRegistration::new("sentinel_intelligence", "start_combat", "sentinel_intelligence::start_combat(boss_index: int)"),
    StdlibFunctionRegistration::new("sentinel_intelligence", "submit", "sentinel_intelligence::submit()"),
    StdlibFunctionRegistration::new("session", "clear", "session::clear()"),
    StdlibFunctionRegistration::new("session", "delete", "session::delete(key: string)"),
    StdlibFunctionRegistration::new("session", "get_bool", "session::get_bool(key: string, default_value: bool)"),
    StdlibFunctionRegistration::new("session", "get_int", "session::get_int(key: string, default_value: int)"),
    StdlibFunctionRegistration::new("session", "get_string", "session::get_string(key: string, default_value: string)"),
    StdlibFunctionRegistration::new("session", "list_keys", "session::list_keys()"),
    StdlibFunctionRegistration::new("session", "set_bool", "session::set_bool(key: string, value: bool)"),
    StdlibFunctionRegistration::new("session", "set_int", "session::set_int(key: string, value: int)"),
    StdlibFunctionRegistration::new("session", "set_string", "session::set_string(key: string, value: string)"),
    StdlibFunctionRegistration::new("spirit", "add_skill_from_pool", "spirit::add_skill_from_pool(spirit_id: int, position: int, skill_id: int)"),
    StdlibFunctionRegistration::new("spirit", "allocate_exp", "spirit::allocate_exp(position: int, exp: int)"),
    StdlibFunctionRegistration::new("spirit", "amend_nature_query_candidates", "spirit::amend_nature_query_candidates()"),
    StdlibFunctionRegistration::new("spirit", "amend_nature_query_eligible_spirit_ids", "spirit::amend_nature_query_eligible_spirit_ids()"),
    StdlibFunctionRegistration::new("spirit", "awaken_blood_gift", "spirit::awaken_blood_gift(position: int, blood_index: int)"),
    StdlibFunctionRegistration::new("spirit", "choose_amend_nature", "spirit::choose_amend_nature(spirit_id: int, catch_time: int, personality: int)"),
    StdlibFunctionRegistration::new("spirit", "equip_blood_gift", "spirit::equip_blood_gift(position: int, blood_index: int)"),
    StdlibFunctionRegistration::new("spirit", "equip_item", "spirit::equip_item(position: int, equipment_server_id: int, equipment_catch_time: int, spirit_id: int, spirit_catch_time: int)"),
    StdlibFunctionRegistration::new("spirit", "fetch_spirit", "spirit::fetch_spirit(spirit_id: int, catch_time: int)"),
    StdlibFunctionRegistration::new("spirit", "get_auto_recover_enabled", "spirit::get_auto_recover_enabled()"),
    StdlibFunctionRegistration::new("spirit", "get_bag_items", "spirit::get_bag_items()"),
    StdlibFunctionRegistration::new("spirit", "get_blood_gift_info", "spirit::get_blood_gift_info(position: int)"),
    StdlibFunctionRegistration::new("spirit", "get_skills", "spirit::get_skills(position: int)"),
    StdlibFunctionRegistration::new("spirit", "get_spirit_bag", "spirit::get_spirit_bag()"),
    StdlibFunctionRegistration::new("spirit", "get_storage_spirit_detail", "spirit::get_storage_spirit_detail(spirit_id: int, catch_time: int)"),
    StdlibFunctionRegistration::new("spirit", "list_abandoned_storage_spirits", "spirit::list_abandoned_storage_spirits()"),
    StdlibFunctionRegistration::new("spirit", "list_equipment_bag", "spirit::list_equipment_bag()"),
    StdlibFunctionRegistration::new("spirit", "list_storage_spirits", "spirit::list_storage_spirits()"),
    StdlibFunctionRegistration::new("spirit", "query_skill_pool", "spirit::query_skill_pool(spirit_id: int, position: int)"),
    StdlibFunctionRegistration::new("spirit", "random_amend_nature", "spirit::random_amend_nature(spirit_id: int, catch_time: int)"),
    StdlibFunctionRegistration::new("spirit", "recover_all_spirits", "spirit::recover_all_spirits()"),
    StdlibFunctionRegistration::new("spirit", "recover_all_spirits_at_hospital", "spirit::recover_all_spirits_at_hospital()"),
    StdlibFunctionRegistration::new("spirit", "restore_spirit", "spirit::restore_spirit(spirit_id: int, position: int)"),
    StdlibFunctionRegistration::new("spirit", "save_strive_add", "spirit::save_strive_add(position: int, pa: int, pd: int, ma: int, md: int, sp: int, hp: int)"),
    StdlibFunctionRegistration::new("spirit", "store_spirit", "spirit::store_spirit(position: int)"),
    StdlibFunctionRegistration::new("spirit", "swap_spirits", "spirit::swap_spirits(first_position: int, second_position: int)"),
    StdlibFunctionRegistration::new("spirit", "switch_skill", "spirit::switch_skill(spirit_id: int, position: int, skill_slot: int, skill_id: int)"),
    StdlibFunctionRegistration::new("spirit", "take_pushed_drops", "spirit::take_pushed_drops()"),
    StdlibFunctionRegistration::new("spirit", "toggle_auto_recover", "spirit::toggle_auto_recover()"),
    StdlibFunctionRegistration::new("spirit", "try_recover_all_spirits", "spirit::try_recover_all_spirits()"),
    StdlibFunctionRegistration::new("spirit", "try_recover_all_spirits_at_hospital", "spirit::try_recover_all_spirits_at_hospital()"),
    StdlibFunctionRegistration::new("spirit", "try_restore_spirit", "spirit::try_restore_spirit(spirit_id: int, position: int)"),
    StdlibFunctionRegistration::new("spirit", "try_store_spirit", "spirit::try_store_spirit(position: int)"),
    StdlibFunctionRegistration::new("spirit", "try_swap_spirits", "spirit::try_swap_spirits(first_position: int, second_position: int)"),
    StdlibFunctionRegistration::new("spirit", "unequip_all_items", "spirit::unequip_all_items(spirit_id: int, spirit_catch_time: int)"),
    StdlibFunctionRegistration::new("spirit", "unequip_item", "spirit::unequip_item(equipment_server_id: int, equipment_catch_time: int, spirit_id: int, spirit_catch_time: int)"),
    StdlibFunctionRegistration::new("spirit", "use_skill_stone_apply", "spirit::use_skill_stone_apply(position: int, item_id: int)"),
    StdlibFunctionRegistration::new("spirit", "use_skill_stone_preview", "spirit::use_skill_stone_preview(position: int, item_id: int)"),
    StdlibFunctionRegistration::new("spirit", "use_skill_stone_replace", "spirit::use_skill_stone_replace(position: int, item_id: int, old_skill_id: int, new_skill_id: int)"),
    StdlibFunctionRegistration::new("spirit", "use_spirit_item", "spirit::use_spirit_item(spirit_id: int, position: int, item_id: int, count: int)"),
    StdlibFunctionRegistration::new("spirit", "use_talent_refresh_item", "spirit::use_talent_refresh_item(spirit_id: int, position: int, item_id: int)"),
    StdlibFunctionRegistration::new("spirit_book", "get_my_spirit_state", "spirit_book::get_my_spirit_state(spirit_id: int)"),
    StdlibFunctionRegistration::new("spirit_book", "get_my_states", "spirit_book::get_my_states()"),
    StdlibFunctionRegistration::new("spirit_book", "get_role_spirit_state", "spirit_book::get_role_spirit_state(uin: int, spirit_id: int)"),
    StdlibFunctionRegistration::new("spirit_book", "get_role_states", "spirit_book::get_role_states(uin: int)"),
    StdlibFunctionRegistration::new("star_tower", "claim_floor_reward", "star_tower::claim_floor_reward(storey_index: int)"),
    StdlibFunctionRegistration::new("star_tower", "claim_top_reward", "star_tower::claim_top_reward(reward_index: int)"),
    StdlibFunctionRegistration::new("star_tower", "full_level", "star_tower::full_level(spirit_id: int, catch_time: int)"),
    StdlibFunctionRegistration::new("star_tower", "query", "star_tower::query()"),
    StdlibFunctionRegistration::new("star_tower", "query_bag", "star_tower::query_bag()"),
    StdlibFunctionRegistration::new("star_tower", "quick_combat", "star_tower::quick_combat(storey: int, storey1: int, sell: bool)"),
    StdlibFunctionRegistration::new("star_tower", "submit_floor", "star_tower::submit_floor(storey_index: int, node_index: int)"),
    StdlibFunctionRegistration::new("star_tower", "submit_top_boss", "star_tower::submit_top_boss()"),
    StdlibFunctionRegistration::new("star_tower", "toggle_auto_sell", "star_tower::toggle_auto_sell()"),
    StdlibFunctionRegistration::new("summon", "cancel_wish", "summon::cancel_wish(pool_version: int)"),
    StdlibFunctionRegistration::new("summon", "draw", "summon::draw(pool_version: int, draw_count: int)"),
    StdlibFunctionRegistration::new("summon", "exchange", "summon::exchange(exchange_kind: int, pool_version: int, item_index: int, count: int)"),
    StdlibFunctionRegistration::new("summon", "query", "summon::query()"),
    StdlibFunctionRegistration::new("summon", "query_data", "summon::query_data()"),
    StdlibFunctionRegistration::new("summon", "query_record", "summon::query_record()"),
    StdlibFunctionRegistration::new("summon", "set_wish", "summon::set_wish(pool_version: int, wish_index: int)"),
    StdlibFunctionRegistration::new("system", "assert", "system::assert(condition: bool, message: string)"),
    StdlibFunctionRegistration::new("system", "format_time", "system::format_time(timestamp: int)"),
    StdlibFunctionRegistration::new("system", "log", "system::log(message: string)"),
    StdlibFunctionRegistration::new("system", "now_ms", "system::now_ms()"),
    StdlibFunctionRegistration::new("system", "random_int", "system::random_int(min_inclusive: int, max_inclusive: int)"),
    StdlibFunctionRegistration::new("system", "sleep", "system::sleep(ms: int)"),
    StdlibFunctionRegistration::new("system", "sleep_until_ms", "system::sleep_until_ms(target_ms: int)"),
    StdlibFunctionRegistration::new("system", "status", "system::status(message: string)"),
    StdlibFunctionRegistration::new("task", "accept", "task::accept(task_id: int)"),
    StdlibFunctionRegistration::new("task", "check_achievement_finish", "task::check_achievement_finish(story_id: int)"),
    StdlibFunctionRegistration::new("task", "complete", "task::complete(task_id: int)"),
    StdlibFunctionRegistration::new("task", "condition_apply_complete", "task::condition_apply_complete(npc_id: int)"),
    StdlibFunctionRegistration::new("task", "condition_query_status", "task::condition_query_status(task_id: int)"),
    StdlibFunctionRegistration::new("task", "get_achievement_list", "task::get_achievement_list()"),
    StdlibFunctionRegistration::new("task", "query_info_list", "task::query_info_list()"),
    StdlibFunctionRegistration::new("task", "query_magic_grow_up_info", "task::query_magic_grow_up_info()"),
    StdlibFunctionRegistration::new("task", "report_progress", "task::report_progress(task_index: int)"),
    StdlibFunctionRegistration::new("taurus", "first_buy_item", "taurus::first_buy_item(item_index: int, count: int)"),
    StdlibFunctionRegistration::new("taurus", "first_buy_spirit", "taurus::first_buy_spirit()"),
    StdlibFunctionRegistration::new("taurus", "first_get_ding", "taurus::first_get_ding()"),
    StdlibFunctionRegistration::new("taurus", "first_get_glue", "taurus::first_get_glue()"),
    StdlibFunctionRegistration::new("taurus", "first_get_leather", "taurus::first_get_leather()"),
    StdlibFunctionRegistration::new("taurus", "first_get_nail", "taurus::first_get_nail()"),
    StdlibFunctionRegistration::new("taurus", "first_mix", "taurus::first_mix(part_index: int)"),
    StdlibFunctionRegistration::new("taurus", "first_query", "taurus::first_query()"),
    StdlibFunctionRegistration::new("taurus", "second_buy_game", "taurus::second_buy_game(game_index: int)"),
    StdlibFunctionRegistration::new("taurus", "second_buy_level", "taurus::second_buy_level(spirit_id: int, catch_time: int)"),
    StdlibFunctionRegistration::new("taurus", "second_evolve", "taurus::second_evolve(spirit_id: int, catch_time: int)"),
    StdlibFunctionRegistration::new("taurus", "second_query", "taurus::second_query()"),
    StdlibFunctionRegistration::new("taurus", "second_query_bag", "taurus::second_query_bag()"),
    StdlibFunctionRegistration::new("taurus", "submit_second_game", "taurus::submit_second_game(game_index: int, score: int)"),
    StdlibFunctionRegistration::new("taurus", "submit_third_npc", "taurus::submit_third_npc()"),
    StdlibFunctionRegistration::new("taurus", "third_buy_level", "taurus::third_buy_level(spirit_id: int, catch_time: int)"),
    StdlibFunctionRegistration::new("taurus", "third_buy_score", "taurus::third_buy_score(kind: int)"),
    StdlibFunctionRegistration::new("taurus", "third_evolve", "taurus::third_evolve(spirit_id: int, catch_time: int)"),
    StdlibFunctionRegistration::new("taurus", "third_get_task", "taurus::third_get_task()"),
    StdlibFunctionRegistration::new("taurus", "third_query", "taurus::third_query()"),
    StdlibFunctionRegistration::new("taurus", "third_query_bag", "taurus::third_query_bag()"),
    StdlibFunctionRegistration::new("three_starters", "fire_buy", "three_starters::fire_buy(catch_time: int)"),
    StdlibFunctionRegistration::new("three_starters", "fire_claim_gift", "three_starters::fire_claim_gift(catch_time: int)"),
    StdlibFunctionRegistration::new("three_starters", "fire_over", "three_starters::fire_over(index: int)"),
    StdlibFunctionRegistration::new("three_starters", "fire_query", "three_starters::fire_query()"),
    StdlibFunctionRegistration::new("three_starters", "fire_query_bag", "three_starters::fire_query_bag()"),
    StdlibFunctionRegistration::new("three_starters", "fire_start", "three_starters::fire_start(index: int)"),
    StdlibFunctionRegistration::new("three_starters", "submit_fire_combat", "three_starters::submit_fire_combat(index: int)"),
    StdlibFunctionRegistration::new("three_starters", "submit_fire_direct", "three_starters::submit_fire_direct(index: int)"),
    StdlibFunctionRegistration::new("three_starters", "submit_sun", "three_starters::submit_sun()"),
    StdlibFunctionRegistration::new("three_starters", "submit_sun_combat", "three_starters::submit_sun_combat()"),
    StdlibFunctionRegistration::new("three_starters", "submit_water", "three_starters::submit_water()"),
    StdlibFunctionRegistration::new("three_starters", "submit_water_combat", "three_starters::submit_water_combat()"),
    StdlibFunctionRegistration::new("three_starters", "sun_buy", "three_starters::sun_buy(catch_time: int)"),
    StdlibFunctionRegistration::new("three_starters", "sun_claim_gift", "three_starters::sun_claim_gift(catch_time: int)"),
    StdlibFunctionRegistration::new("three_starters", "sun_query", "three_starters::sun_query()"),
    StdlibFunctionRegistration::new("three_starters", "sun_query_bag", "three_starters::sun_query_bag()"),
    StdlibFunctionRegistration::new("three_starters", "sun_start_collect", "three_starters::sun_start_collect()"),
    StdlibFunctionRegistration::new("three_starters", "sun_start_combat", "three_starters::sun_start_combat()"),
    StdlibFunctionRegistration::new("three_starters", "water_buy", "three_starters::water_buy(catch_time: int)"),
    StdlibFunctionRegistration::new("three_starters", "water_claim_gift", "three_starters::water_claim_gift(catch_time: int)"),
    StdlibFunctionRegistration::new("three_starters", "water_query", "three_starters::water_query()"),
    StdlibFunctionRegistration::new("three_starters", "water_query_bag", "three_starters::water_query_bag()"),
    StdlibFunctionRegistration::new("treasure_realm", "boost_by_item", "treasure_realm::boost_by_item(index: int)"),
    StdlibFunctionRegistration::new("treasure_realm", "boost_by_vip", "treasure_realm::boost_by_vip()"),
    StdlibFunctionRegistration::new("treasure_realm", "buy", "treasure_realm::buy(index: int)"),
    StdlibFunctionRegistration::new("treasure_realm", "claim_gift", "treasure_realm::claim_gift(index: int)"),
    StdlibFunctionRegistration::new("treasure_realm", "query", "treasure_realm::query()"),
    StdlibFunctionRegistration::new("treasure_realm", "start_combat", "treasure_realm::start_combat()"),
    StdlibFunctionRegistration::new("treasure_realm", "submit", "treasure_realm::submit()"),
    StdlibFunctionRegistration::new("type_ladder", "cancel_match", "type_ladder::cancel_match()"),
    StdlibFunctionRegistration::new("type_ladder", "query_info", "type_ladder::query_info()"),
    StdlibFunctionRegistration::new("type_ladder", "query_rank", "type_ladder::query_rank()"),
    StdlibFunctionRegistration::new("type_ladder", "recover_spirits", "type_ladder::recover_spirits()"),
    StdlibFunctionRegistration::new("type_ladder", "try_recover_spirits", "type_ladder::try_recover_spirits()"),
    StdlibFunctionRegistration::new("unicorn", "claim_cultivation_reward", "unicorn::claim_cultivation_reward()"),
    StdlibFunctionRegistration::new("unicorn", "evolve", "unicorn::evolve(stage: int, catch_time: int)"),
    StdlibFunctionRegistration::new("unicorn", "exchange_skill_stone", "unicorn::exchange_skill_stone(skill: int, cost_kind: int)"),
    StdlibFunctionRegistration::new("unicorn", "harvest", "unicorn::harvest()"),
    StdlibFunctionRegistration::new("unicorn", "one_key_evolve", "unicorn::one_key_evolve(stage: int, catch_time: int)"),
    StdlibFunctionRegistration::new("unicorn", "query", "unicorn::query()"),
    StdlibFunctionRegistration::new("unicorn", "query_evolution_bag", "unicorn::query_evolution_bag(stage: int)"),
    StdlibFunctionRegistration::new("unicorn", "start_cultivation", "unicorn::start_cultivation()"),
    StdlibFunctionRegistration::new("unicorn", "submit_cultivation_task", "unicorn::submit_cultivation_task(task: int)"),
    StdlibFunctionRegistration::new("unicorn", "submit_mini_game", "unicorn::submit_mini_game()"),
    StdlibFunctionRegistration::new("unicorn", "submit_summon", "unicorn::submit_summon(slot: int)"),
    StdlibFunctionRegistration::new("unicorn", "summon", "unicorn::summon()"),
    StdlibFunctionRegistration::new("virgo", "bell_fox_buy_tail", "virgo::bell_fox_buy_tail(count: int)"),
    StdlibFunctionRegistration::new("virgo", "bell_fox_buy_wish", "virgo::bell_fox_buy_wish()"),
    StdlibFunctionRegistration::new("virgo", "bell_fox_exchange_item", "virgo::bell_fox_exchange_item(exchange_position: int)"),
    StdlibFunctionRegistration::new("virgo", "bell_fox_exchange_spirit", "virgo::bell_fox_exchange_spirit()"),
    StdlibFunctionRegistration::new("virgo", "bell_fox_query_status", "virgo::bell_fox_query_status()"),
    StdlibFunctionRegistration::new("virgo", "find_halidom_buy_pass", "virgo::find_halidom_buy_pass()"),
    StdlibFunctionRegistration::new("virgo", "find_halidom_buy_search_count", "virgo::find_halidom_buy_search_count()"),
    StdlibFunctionRegistration::new("virgo", "find_halidom_buy_top_level", "virgo::find_halidom_buy_top_level(spirit_id: int, catch_time: int)"),
    StdlibFunctionRegistration::new("virgo", "find_halidom_clean", "virgo::find_halidom_clean(relic_index: int)"),
    StdlibFunctionRegistration::new("virgo", "find_halidom_list_spirits", "virgo::find_halidom_list_spirits()"),
    StdlibFunctionRegistration::new("virgo", "find_halidom_put_spirit", "virgo::find_halidom_put_spirit(spirit_id: int, catch_time: int)"),
    StdlibFunctionRegistration::new("virgo", "find_halidom_query", "virgo::find_halidom_query(altar: bool)"),
    StdlibFunctionRegistration::new("virgo", "serve_god_accept_task", "virgo::serve_god_accept_task()"),
    StdlibFunctionRegistration::new("virgo", "serve_god_buy_unlock", "virgo::serve_god_buy_unlock()"),
    StdlibFunctionRegistration::new("virgo", "serve_god_finish_task", "virgo::serve_god_finish_task()"),
    StdlibFunctionRegistration::new("virgo", "serve_god_give_up_task", "virgo::serve_god_give_up_task()"),
    StdlibFunctionRegistration::new("virgo", "serve_god_query", "virgo::serve_god_query()"),
    StdlibFunctionRegistration::new("virgo", "serve_god_query_bag", "virgo::serve_god_query_bag()"),
    StdlibFunctionRegistration::new("virgo", "serve_god_upgrade", "virgo::serve_god_upgrade(spirit_id: int, catch_time: int)"),
    StdlibFunctionRegistration::new("virgo", "serve_god_upgrade_to_100", "virgo::serve_god_upgrade_to_100(spirit_id: int, catch_time: int)"),
    StdlibFunctionRegistration::new("virgo", "submit_serve_god_boss", "virgo::submit_serve_god_boss()"),
    StdlibFunctionRegistration::new("weather", "name", "weather::name(weather: int)"),
    StdlibFunctionRegistration::new("weather", "names", "weather::names()"),
];
