use super::StdlibFunctionDetails;

pub fn docs() -> Vec<StdlibFunctionDetails> {
    vec![
        super::stdlib_doc!("sagittarius", "first_add_map", return_type: "SagittariusFirstInfo", "更新射手宫的 first_add_map 操作。", params: [], returns: "返回 SagittariusFirstInfo。", examples: ["let result = sagittarius::first_add_map();"]),
        super::stdlib_doc!("sagittarius", "first_add_speed", return_type: "SagittariusFirstInfo", "更新射手宫的 first_add_speed 操作。", params: [], returns: "返回 SagittariusFirstInfo。", examples: ["let result = sagittarius::first_add_speed();"]),
        super::stdlib_doc!("sagittarius", "first_complete", return_type: "SagittariusFirstInfo", "提交射手宫的 first_complete 操作。", params: ["index" => "目标索引。"], returns: "返回 SagittariusFirstInfo。", examples: ["let result = sagittarius::first_complete(0);"]),
        super::stdlib_doc!("sagittarius", "first_claim_spirit", return_type: "SagittariusFirstInfo", "领取射手宫的 first_claim_spirit 操作。", params: [], returns: "返回 SagittariusFirstInfo。", examples: ["let result = sagittarius::first_claim_spirit();"]),
        super::stdlib_doc!("sagittarius", "first_pick_shine", return_type: "SagittariusFirstInfo", "执行射手宫的 first_pick_shine 操作。", params: [], returns: "返回 SagittariusFirstInfo。", examples: ["let result = sagittarius::first_pick_shine();"]),
        super::stdlib_doc!("sagittarius", "first_query", return_type: "SagittariusFirstInfo", "查询射手宫的 first_query 操作。", params: [], returns: "返回 SagittariusFirstInfo。", examples: ["let result = sagittarius::first_query();"]),
        super::stdlib_doc!("sagittarius", "first_query_scene", return_type: "SagittariusFirstInfo", "查询射手宫的 first_query_scene 操作。", params: [], returns: "返回 SagittariusFirstInfo。", examples: ["let result = sagittarius::first_query_scene();"]),
        super::stdlib_doc!("sagittarius", "first_show_map", return_type: "SagittariusFirstInfo", "执行射手宫的 first_show_map 操作。", params: [], returns: "返回 SagittariusFirstInfo。", examples: ["let result = sagittarius::first_show_map();"]),
        super::stdlib_doc!("sagittarius", "submit_first", return_type: "SagittariusFirstInfo", "提交射手宫的 submit_first 操作。", params: [], returns: "返回 SagittariusFirstInfo。", examples: ["let result = sagittarius::submit_first();"]),
        super::stdlib_doc!("sagittarius", "second_buy_up", return_type: "SagittariusSecondInfo", "购买射手宫的 second_buy_up 操作。", params: ["spirit_id" => "宠物 ID。", "catch_time" => "宠物捕获时间。"], returns: "返回 SagittariusSecondInfo。", examples: ["let result = sagittarius::second_buy_up(0, 0);"]),
        super::stdlib_doc!("sagittarius", "second_level_up", return_type: "SagittariusSecondInfo", "提升射手宫的 second_level_up 操作。", params: ["spirit_id" => "宠物 ID。", "catch_time" => "宠物捕获时间。"], returns: "返回 SagittariusSecondInfo。", examples: ["let result = sagittarius::second_level_up(0, 0);"]),
        super::stdlib_doc!("sagittarius", "second_query", return_type: "SagittariusSecondInfo", "查询射手宫的 second_query 操作。", params: [], returns: "返回 SagittariusSecondInfo。", examples: ["let result = sagittarius::second_query();"]),
        super::stdlib_doc!("sagittarius", "second_query_bag", return_type: "SagittariusSecondInfo", "查询射手宫二阶背包状态。", params: ["bag_type" => "背包查询类型。"], returns: "返回 SagittariusSecondInfo。", examples: ["let result = sagittarius::second_query_bag(0);"]),
        super::stdlib_doc!("sagittarius", "second_random", return_type: "SagittariusSecondInfo", "执行射手宫的 second_random 操作。", params: [], returns: "返回 SagittariusSecondInfo。", examples: ["let result = sagittarius::second_random();"]),
        super::stdlib_doc!("sagittarius", "second_spirit_up", return_type: "SagittariusSecondInfo", "执行射手宫的 second_spirit_up 操作。", params: ["spirit_id" => "宠物 ID。", "catch_time" => "宠物捕获时间。"], returns: "返回 SagittariusSecondInfo。", examples: ["let result = sagittarius::second_spirit_up(0, 0);"]),
        super::stdlib_doc!("sagittarius", "second_start", return_type: "SagittariusSecondInfo", "开始射手宫的 second_start 操作。", params: [], returns: "返回 SagittariusSecondInfo。", examples: ["let result = sagittarius::second_start();"]),
        super::stdlib_doc!("sagittarius", "second_task", return_type: "SagittariusSecondInfo", "执行射手宫的 second_task 操作。", params: ["task_type" => "任务类型。"], returns: "返回 SagittariusSecondInfo。", examples: ["let result = sagittarius::second_task(0);"]),
        super::stdlib_doc!("sagittarius", "third_add_challenge_count", return_type: "SagittariusThirdInfo", "更新射手宫的 third_add_challenge_count 操作。", params: [], returns: "返回 SagittariusThirdInfo。", examples: ["let result = sagittarius::third_add_challenge_count();"]),
        super::stdlib_doc!("sagittarius", "third_buy_evolve", return_type: "SagittariusThirdInfo", "购买射手宫的 third_buy_evolve 操作。", params: ["spirit_id" => "宠物 ID。", "catch_time" => "宠物捕获时间。"], returns: "返回 SagittariusThirdInfo。", examples: ["let result = sagittarius::third_buy_evolve(0, 0);"]),
        super::stdlib_doc!("sagittarius", "third_buy_spirit", return_type: "SagittariusThirdInfo", "购买射手宫的 third_buy_spirit 操作。", params: [], returns: "返回 SagittariusThirdInfo。", examples: ["let result = sagittarius::third_buy_spirit();"]),
        super::stdlib_doc!("sagittarius", "third_buy_star_num", return_type: "SagittariusThirdInfo", "购买射手宫三阶星数奖励。", params: ["score_index" => "积分项索引。"], returns: "返回 SagittariusThirdInfo。", examples: ["let result = sagittarius::third_buy_star_num(0);"]),
        super::stdlib_doc!("sagittarius", "third_query", return_type: "SagittariusThirdInfo", "查询射手宫的 third_query 操作。", params: [], returns: "返回 SagittariusThirdInfo。", examples: ["let result = sagittarius::third_query();"]),
        super::stdlib_doc!("sagittarius", "third_query_bag", return_type: "SagittariusThirdInfo", "查询射手宫的 third_query_bag 操作。", params: [], returns: "返回 SagittariusThirdInfo。", examples: ["let result = sagittarius::third_query_bag();"]),
        super::stdlib_doc!("sagittarius", "submit_third", return_type: "SagittariusThirdInfo", "处理战斗射手宫的 submit_third 操作。", params: ["boss_index" => "首领索引。"], returns: "返回 SagittariusThirdInfo。", examples: ["let result = sagittarius::submit_third(0);"]),
        super::stdlib_doc!("sagittarius", "third_up", return_type: "SagittariusThirdInfo", "执行射手宫的 third_up 操作。", params: ["spirit_id" => "宠物 ID。", "catch_time" => "宠物捕获时间。"], returns: "返回 SagittariusThirdInfo。", examples: ["let result = sagittarius::third_up(0, 0);"]),
    ]
}
