//! 共享类型定义

mod action;
mod activities;
mod combat;
mod common;
mod friend;
mod game;
mod home;
mod incubative_machine;
mod jump_machine;
mod ladder;
mod manor;
mod news;
mod pet_egg;
mod pet_training;
mod play_guide;
mod profile;
mod reclaim_goods;
mod remote_state;
mod rhai;
mod scene;
mod spirit;
mod spirit_book;
mod star_tower;
mod static_data;
mod task;
mod zodiac;

pub use action::*;
pub use activities::*;
pub use combat::*;
pub use common::*;
pub use friend::*;
pub use game::*;
pub use home::*;
pub use incubative_machine::*;
pub use jump_machine::*;
pub use ladder::*;
pub use manor::*;
pub use news::*;
pub use pet_egg::*;
pub use pet_training::*;
pub use play_guide::*;
pub use profile::*;
pub use reclaim_goods::*;
pub use remote_state::*;
pub use scene::*;
pub use spirit::*;
pub use spirit_book::*;
pub use star_tower::*;
pub use static_data::*;
pub use task::*;
pub use zodiac::*;

pub(crate) use rhai::register_rhai_getters;
